---
title: "Education Graphing"
output: html_notebook
---

##Graphing the education data

Loading libraries
```{r libraries, message = FALSE}
library(showtext)
library(classInt)
library(ggthemes)
library(reshape2)
library(leaflet)
library(rgdal)
library(htmlwidgets)
library(RColorBrewer)
library(tidyverse)
```

Reading in data
```{r data}
setwd("C:/Users/natek/Documents/Github/glp_website/data")
educ_data = read_csv("education peer data.csv")

rescale <- function(x){new_value <- x*100}
educ_data[ ,c(9:21, 23:40)] = apply(educ_data[ ,c(9:21, 23:40)], 2, rescale)
educ_data_15 <- educ_data %>% filter(year == 2015)

```

The code for the rankings graphs
```{r rankings}
rank_and_nb_group<-function(df, var, order="Descending", peers="Current",
                            plot_title="", y_title = "Percent", caption_text = ""){
  df$var <- df[[var]]
  if(peers=="Current"){
    df<-subset(df,current_peer ==1)
  }
  if(peers=="Baseline"){
    df<-subset(df,baseline_peer ==1)
  }
  if(order=="Descending"){
    d.order<-df[order(-df$var),]
  }
  if(order=="Ascending"){
    d.order<-df[order(df$var),]
  }
  ranks<-1:length(df$var)
  d.rank<-cbind(d.order,ranks)
  names<-paste(d.rank$ranks,".",sep="")
  names<-paste(names,d.rank$city)
  d.graph<-cbind(d.rank,names)
  
  breaks<-classIntervals(d.graph$var,3,style="jenks")
  d.graph$color<-NA
  d.graph$color[d.graph$var<=breaks$brks[2]]<-"green"
  d.graph$color[d.graph$var>breaks$brks[2] & d.graph$var<=breaks$brks[3]]<-"yellow"
  d.graph$color[d.graph$var>breaks$brks[3]]<-"red"
  d.graph$round<-format(round(d.graph$var,1),nsmall=1)
  d.graph$textfont<-"Museo Sans 300"
  d.graph$textfont[d.graph$city == "Louisville"]<-"Museo Sans Italic"
  d.graph$linecolor<-"white"
  d.graph$linecolor[d.graph$city == "Louisville"]<-"#00a9b7"
  d.graph$textcolor<-"black"
  d.graph$textcolor[d.graph$city == "Louisville"]<-"#00a9b7"
  
  
  p<-ggplot(data=d.graph,aes(x=factor(names, levels=rev(unique(names))),
                             y=var,fill=factor(color)))+guides(fill=FALSE)
  p<-p+geom_bar(stat="identity",color=rev(d.graph$linecolor), size = 1)+coord_flip()+theme_tufte()
  if(order=="Ascending"){
    p<-p+scale_fill_manual(values=c("#96ca4f","#db2834","#ffd600"))
  }
  if(order=="Descending"){
    p<-p+scale_fill_manual(values=c("#db2834","#96ca4f","#ffd600"))
  }
  p <- p + theme(text = element_text(family = "Museo Sans 300"),
                plot.title = element_text(size = 18, hjust = .5),
                axis.text.y=element_text(hjust=0, family = rev(d.graph$textfont),
                                         size=12, color = rev(d.graph$textcolor)),
                axis.ticks=element_blank(),
                axis.text.x = element_blank(),
                plot.caption = element_text(),
                plot.subtitle = element_text(hjust = .5))
  p <- p+geom_text(aes(label=round),hjust=1.1, size=5, family = "Museo Sans 300")
  p<-p+labs(title = plot_title, y= y_title,
            x = "", caption = caption_text)
  p
}

```

Adding fonts
```{r}
font.add("Museo Sans 300", "C:/Users/natek/Documents/fonts/MuseoSans/MuseoSans_300.otf")
font.add("Museo Sans Italic", "C:/Users/natek/Documents/fonts/MuseoSans/MuseoSans_300_Italic.otf")

```


```{r, message = FALSE}
setwd("C:/Users/natek/Documents/images")

jpeg("edu_under_5_pov_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "under_5_per", order = "Ascending",
                  plot_title = "Children Under 5 in Poverty, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_five_to_17_pov_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "five_to_17_per", order = "Ascending",
                  plot_title = "Children Ages 5 to 17 in Poverty, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_child_pov_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "child_per", order = "Ascending",
                  plot_title = "Child Poverty, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_bach_plus_all_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "bach_plus_per_all", 
                  plot_title = "Bachelor's Degree or Higher, All Races, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002")
showtext.end()
dev.off()

jpeg("edu_bach_plus_black_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "bach_plus_per_black", 
                  plot_title = "Bachelor's Degree or Higher, Black, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002B")
showtext.end()
dev.off()

jpeg("edu_25_64_assoc_plus_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_64_assoc_plus", 
                  plot_title = "Associate's Degree or Higher, Ages 25-64, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_64_bach_plus_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_64_bach_plus", 
                  plot_title = "Bachelor's Degree or Higher, Ages 25-64, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_64_grad_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_64_grad", 
                  plot_title = "Graduate Degree, Ages 25-64, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_assoc_plus_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_34_assoc_plus", 
                  plot_title = "Associate's Degree or Higher, Ages 25-34, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_bach_plus_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_34_bach_plus", 
                  plot_title = "Bachelor's Degree or Higher, Ages 25-34, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_grad_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_34_grad", 
                  plot_title = "Graduate Degree, Ages 25-34, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()


jpeg("edu_per_25_64_bach_plus_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_25_64_bach_plus", 
                  plot_title = "Bachelor's Degree or Higher, Ages 25-64, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_bach_plus_hispanic_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "bach_plus_per_hispanic", 
                  plot_title = "Bachelor's Degree or Higher, Hispanic, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002I")
showtext.end()
dev.off()

jpeg("edu_bach_plus_white_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "bach_plus_per_white", 
                  plot_title = "Bachelor's Degree or Higher, White, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002A")
showtext.end()
dev.off()

jpeg("edu_enrolled_3_4_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "enrolled_3_4", 
                  plot_title = "Children ages 3 and 4 enrolled in preschool, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table S1401")
showtext.end()
dev.off()

jpeg("edu_per_high_wage_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(educ_data_15, "per_high_wage", 
                  plot_title = "Population in High Wage Occupations, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table S2401")
showtext.end()
dev.off()
```

Now two functions for taking rolling means that will be used for the graph trendlines function
```{r rolling means}
rollmean3 <- function(x){
  n <- length(x)
  y <- NA
  for(i in 1:n){
    y[i] <- mean(c(x[i-1],x[i],x[i+1]))
    y[1] <- NA
  }
  y
}

rollmean5 <- function(x){
  n <- length(x)
  y <- NA
  for(i in 1:n){
    y[i] <- mean(c(x[i-2],x[i-1],x[i],x[i+1],x[i+2]))
    y[1] <- NA
    y[2] <- NA
  }
  y
}
```

And then the function for graphing trendlines
```{r trendline graph}
graph_trendline<-function(df,var, plot_title="",y_title="Percent", peers = "Current", 
                          caption_text = "", subtitle_text = "", rollmean = 3){
  df$var <- df[[var]]
  df = df %>% filter(year != 2016)
  
  if(peers=="Current"){
    df.wol <- subset(df,current_peer == 1 & FIPS!=21111)
  }
  
  if(peers=="Baseline"){
    df.wol <- subset(df,baseline_peer == 1 & FIPS!=21111)
  }
  
  output_wol = df %>% 
    group_by(year) %>%
    summarise(first_quarter = quantile(var, prob = 0.25, na.rm = TRUE),
              mean = mean(var),
              third_quarter = quantile(var, prob = 0.75, na.rm = TRUE))
  
  lville = df %>% 
    filter(FIPS == 21111) %>% 
    select(var, year)
  
  dat = full_join(lville, output_wol, by = "year")
  
  if (rollmean == 3){
    dat$var = rollmean3(dat$var)
    dat$first_quarter = rollmean3(dat$first_quarter)
    dat$mean = rollmean3(dat$mean)
    dat$third_quarter = rollmean3(dat$third_quarter)
    dat <- dat %>% filter(year > 2005 & year < 2015)
  }
  
  if (rollmean == 5){
    dat$var = rollmean5(dat$var)
    dat$first_quarter = rollmean5(dat$first_quarter)
    dat$mean = rollmean5(dat$mean)
    dat$third_quarter = rollmean5(dat$third_quarter)
    dat = dat %>% filter(year > 2006 & year < 2014)
  }
  
  data_long <- melt(dat, id="year")
  data_long$variable = factor(data_long$variable, levels = c("var", "third_quarter", "mean", "first_quarter"))
  
  p <- ggplot(data=data_long,aes(x=year,y=value,colour=variable,linetype=variable))+
              geom_point(size = 1.8)+
              geom_line(size = 1)
  p <- p + theme_bw()
  midpoint <- (max(data_long$value)+min(data_long$value))/2
  border_space <- .1 * midpoint
  p <- p + ylim(c(min(data_long$value) - border_space, max(data_long$value + border_space)))
  p<-p+scale_x_continuous(breaks=seq(2005, 2015, 2))
  cPalette <- c("#00a9b7","grey50", "black","grey50")
  p<-p+scale_colour_manual(values=cPalette,
                           labels=c("Louisville", "75th Percentile", "Peer City Mean", "25th Percentile"))+
    scale_linetype_manual(values=c("solid","dashed","dashed","dashed"),
                          labels=c("Louisville", "75th Percentile", "Peer City Mean", "25th Percentile"))
  p<-p+theme(text = element_text(family = "Museo Sans 300"),
             legend.title=element_blank(),
             legend.position = "top",
             axis.text=element_text(size=12, family = "Museo Sans 300"),
             axis.ticks.y=element_blank(),
             plot.title=element_text(size=18, hjust=.5, family = "Museo Sans 300",
                                     margin=margin(b=10,unit="pt")),
             legend.text=element_text(size=12, family = "Museo Sans 300"),
             plot.caption = element_text(family = "Museo Sans 300"),
             plot.subtitle = element_text(family = "Museo Sans 300", hjust = 0.5))
  p<-p+labs(title=plot_title,x="Year",
            y=y_title, caption = caption_text, subtitle = subtitle_text)
  p
}
```



```{r}
setwd("C:/Users/natek/Documents/images")

jpeg("edu_under_5_pov_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "under_5_per",
                  plot_title = "Children Under 5 in Poverty",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_five_to_17_pov_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "five_to_17_per", 
                  plot_title = "Children Ages 5 to 17 in Poverty",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_child_pov_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "child_per",
                  plot_title = "Child Poverty",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B17001")
showtext.end()
dev.off()

jpeg("edu_bach_plus_all_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "bach_plus_per_all",
                  plot_title = "Bachelor's Degree or Higher, All Races",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002")
showtext.end()
dev.off()

jpeg("edu_bach_plus_black_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "bach_plus_per_black",
                  plot_title = "Bachelor's Degree or Higher, Black",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002B")
showtext.end()
dev.off()

jpeg("edu_25_64_assoc_plus_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_64_assoc_plus",
                  plot_title = "Associate's Degree or Higher, Ages 25-64",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_64_bach_plus_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_64_bach_plus",
                  plot_title = "Bachelor's Degree or Higher, Ages 25-64",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_64_grad_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_64_grad",
                  plot_title = "Graduate Degree, Ages 25-64",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_assoc_plus_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_34_assoc_plus",
                  plot_title = "Associate's Degree or Higher, Ages 25-34",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_bach_plus_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_34_bach_plus",
                  plot_title = "Bachelor's Degree or Higher, Ages 25-34",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_25_34_grad_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_34_grad",
                  plot_title = "Graduate Degree, Ages 25-34",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()


jpeg("edu_per_25_64_bach_plus_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_25_64_bach_plus",
                  plot_title = "Bachelor's Degree or Higher, Ages 25-64",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15001")
showtext.end()
dev.off()

jpeg("edu_bach_plus_hispanic_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "bach_plus_per_hispanic",
                  plot_title = "Bachelor's Degree or Higher, Hispanic",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002I")
showtext.end()
dev.off()

jpeg("edu_bach_plus_white_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "bach_plus_per_white",
                  plot_title = "Bachelor's Degree or Higher, White",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table B15002A")
showtext.end()
dev.off()

jpeg("edu_enrolled_3_4_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "enrolled_3_4",
                  plot_title = "Children ages 3 and 4 enrolled in preschool",
                  subtitle = "5-year rolling average",
                  rollmean = 5,
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table S1401")
showtext.end()
dev.off()

jpeg("edu_per_high_wage_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(educ_data, "per_high_wage",
                  plot_title = "Population in High Wage Occupations",
                  subtitle = "3-year rolling average",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table S2401")
showtext.end()
dev.off()
```

Adding mapping data
```{r}
setwd("C:/Users/natek/Documents/Github/glp_website/data")
map_data = read_csv("education map data.csv")

rescale <- function(x){new_value <- x*100}
map_data[ ,c(5:13, 15)] = apply(map_data[ ,c(5:13, 15)], 2, rescale)

```

Reading in data for mapping
```{r}

setwd("C:/Users/natek/Documents/Github/glp_website/data")
map_jc = readOGR("JC Tracts", layer = "JC Tracts",
                 GDAL1_integer64_policy = TRUE)

map_jc@data<-full_join(map_jc@data, map_data, by = c('GEO_ID' = 'Id'))

map_jc@data$tract_num <- substr(map_jc@data$Id2, 6, 11)

map_jc@data$l_line1 <- paste("Tract #:", map_jc@data$tract_num, "in the")
map_jc@data$l_line2 <- paste(map_jc@data$Neighborhood, "neighborhood")


```

Defining a function for mapping
```{r}
make_map <- function(var, name, order = "Descending"){
  map_jc@data$var <- map_jc@data[[var]]
  map_jc@data$l_line3 <- paste(name, ": ", round(map_jc@data$var, 0), "%", sep = "")

labels <- sprintf(
  "%s<br/>%s<br/>%s",
  map_jc@data$l_line1, map_jc@data$l_line2, map_jc@data$l_line3
) %>% lapply(htmltools::HTML)


if(order == "Ascending"){
pal <- rev(brewer.pal(11, "RdYlGn"))
}

if(order == "Descending"){
pal <- brewer.pal(11, "RdYlGn")
}

pal <- colorNumeric(
  palette = pal,
  domain = map_jc@data$var
)

title_text <- paste(name, "(%)")

m <- leaflet(map_jc) %>%
  addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              fillColor = ~pal(var),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"))%>%
  addLegend(pal = pal, values = ~var, opacity = 0.7, title = title_text,
            position = "bottomright")

m
}
```

Making and saving maps
```{r}
setwd("C:/Users/natek/Documents/images")
m <- make_map("child_per", "Child Poverty", order = "Ascending")
saveWidget(m, "edu_child_pov_map.html")

m <- make_map("per_25_64_assoc_plus", "Associate Degrees, 25-64")
saveWidget(m, "edu_25_64_assoc_map.html")

m <- make_map("per_25_64_bach_plus", "Bachelor's Degrees, 25-64")
saveWidget(m, "edu_25_64_bach_map.html")

m <- make_map("per_25_64_grad", "Graduate Degrees, 25-64")
saveWidget(m, "edu_25_64_grad_map.html")

m <- make_map("per_25_34_assoc_plus", "Associate Degrees, 25-34")
saveWidget(m, "edu_assoc_25_34_map.html")

m <- make_map("per_25_34_bach_plus", "Bachelor's Degrees, 25-34")
saveWidget(m, "edu_25_34_bach_map.html")

m <- make_map("per_25_34_grad", "Graduate Degrees, 25-34")
saveWidget(m, "edu_25_34_grad_map.html")

m <- make_map("per_high_wage", "High Wage Occupations")
saveWidget(m, "edu_per_high_wage_map.html")
```

