---
title: "edu_data_pull"
output: html_notebook
---

Code for pulling education data

```{r "setup", include=FALSE}
require("knitr")
opts_knit$set(root.dir = "~/Desktop/glp_website")
```

Loading Libraries
```{r}
library(showtext)
library(reshape2)
library(classInt)
library(ggthemes)
library(tidyverse)
library(magrittr)
```

```{r}
acs_time<-function(folder, starting.year=2005){
  initial_wd <- getwd()
  directory <- paste(initial_wd, folder, sep = "")
  setwd(directory)
  file_names<-list.files()
  n<-length(file_names)
  y<-starting.year
  for (i in 1:n){
    data<-read.csv(file_names[i],header=TRUE, skip=1, stringsAsFactors = FALSE)
    names(data)[names(data) == 'Id2'] <- 'FIPS'
    all.peers <-subset(data, data$FIPS == 1073 |data$FIPS == 37119
                       |data$FIPS == 39061 |data$FIPS == 39049
                       |data$FIPS == 26081 |data$FIPS == 37081
                       |data$FIPS == 45045 |data$FIPS == 18097
                       |data$FIPS == 29095 |data$FIPS == 47093
                       |data$FIPS == 21111 |data$FIPS == 47157
                       |data$FIPS == 47037 |data$FIPS == 40109
                       |data$FIPS == 31055 |data$FIPS == 29189
                       |data$FIPS == 29510
                       |data$FIPS == 40143 |data$FIPS == 39113
                       |data$FIPS == 12031 |data$FIPS == 37183
                       |data$FIPS == 37183 |data$FIPS == 51760)
    
    all.peers$year<-y
    y<-y+1
    
    if(i==1){
     df<-all.peers 
    }
    else{
      names(all.peers)<-names(df)
      df<-rbind(df, all.peers)
    }
  }
  setwd(initial_wd)
  df
}

ccr_read <- function(folder) {
  initial_wd <- getwd()
  directory <- paste(initial_wd, folder, sep = "/")
  file_names <- list.files(directory)
  n <- length(file_names)
  for (i in 1:n) {
    data <-
      read_csv(paste(directory, file_names[i], sep = "/"),
               skip = 0,
               progress = FALSE, 
               col_types = cols(PCT_CCR_NO_BONUS = col_double(),
                                NBR_GRADUATES_WITH_DIPLOMA = col_double()))
    data$SCH_NAME[data$SCH_NAME == "--District Total--"] = "---District Total---"
    data %<>% filter(SCH_NAME == "---District Total---")%>%
      select(school_year = SCH_YEAR, dist_name = DIST_NAME, SCH_NAME,
                     label = DISAGG_LABEL, pct_ccr = PCT_CCR_NO_BONUS,
                     number_grads = NBR_GRADUATES_WITH_DIPLOMA)

    if (i == 1) {
      df <- data
    }
    else{

      df <- bind_rows(df, data)
    }
  }
  df
}

act_read <- function(folder) {
  initial_wd <- getwd()
  directory <- paste(initial_wd, folder, sep = "/")
  file_names <- list.files(directory)
  n <- length(file_names)
  for (i in 1:n) {
    data <-
      read_csv(paste(directory, file_names[i], sep = "/"),
               skip = 0,
               progress = FALSE, 
               col_types = cols(STDNT_TESTED_CNT = col_double(),
                                ENGLISH_MEAN_SCORE = col_double(),
                                MATHEMATICS_MEAN_SCORE = col_double(),
                                READING_MEAN_SCORE = col_double(),
                                SCIENCE_MEAN_SCORE = col_double(),
                                COMPOSITE_MEAN_SCORE = col_double()))
    data$SCH_NAME[data$SCH_NAME == "--- District Total ---"] = "---District Total---"
    data %<>% filter(SCH_NAME == "---District Total---")%>%
      select(school_year = SCH_YEAR, dist_name = DIST_NAME, SCH_NAME,
             label = DISAGG_LABEL,
             num_students_tested = STDNT_TESTED_CNT,
             english_score = ENGLISH_MEAN_SCORE,
             math_score = MATHEMATICS_MEAN_SCORE,
             reading_score = READING_MEAN_SCORE,
             science_score = SCIENCE_MEAN_SCORE,
             composite_score = COMPOSITE_MEAN_SCORE)
    
    if (i == 1) {
      df <- data
    }
    else{
      
      df <- bind_rows(df, data)
    }
  }
  df
}

rename_cols <- function(df, text){
  names <- colnames(df)
  new <- paste(names, text, sep = "_")
  colnames(df) <- new
  df
}

tidy <- function(data, var, key){
  data$var <- data[[var]]
  data$key <- data[[key]]
  data %<>% mutate(key = tolower(gsub(" ", "_", key)))
  data$key[data$key == "white_(non-hispanic)"] = "white"
  data %<>% select(var, key, year, dist_name) %>%
    spread(key = key, value = var)
  data = bind_cols(data[,1:2], rename_cols(data[,3:9], var))
  data
}

restore_ky_ed_data <- function(data){
  var_names <- colnames(data)
  var_names <- var_names[4:11]
  n <- length(var_names)
  for(i in 1:n){
    df = tidy(data, var_names[i], key = "label")
    if(i == 1){
      tidy_df <- df
    }
    else{
      tidy_df <- left_join(tidy_df, df, by = c("year", "dist_name"))
    }
  }
  return(tidy_df)
}
```

Reading in ACS Data
```{r}
data = acs_time("/input data/educ_input_data/B17001")

data = data %>%
mutate(
under_5_per = (
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years
) /
(
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....Under.5.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....Under.5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years
),
five_to_17_under =  Estimate..Income.in.the.past.12.months.below.poverty.level....Male....5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....6.to.11.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....12.to.14.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....15.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....16.and.17.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....6.to.11.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....12.to.14.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....15.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....16.and.17.years,
five_to_17_over =  Estimate..Income.in.the.past.12.months.below.poverty.level....Male....5.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....6.to.11.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....12.to.14.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....15.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....16.and.17.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....5.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....6.to.11.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....12.to.14.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....15.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....16.and.17.years,
five_to_17_per = five_to_17_under / (five_to_17_over + five_to_17_under),
child_under = five_to_17_under +
Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years +
Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years,
child_over = five_to_17_over +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....Under.5.years +
Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....Under.5.years,
child_per = child_under / (child_over + child_under)
)

child_pov_data = data %>%
select(FIPS, year, under_5_per, five_to_17_per, child_per)



data = acs_time("/input data/educ_input_data/S1401/Y5to7")
data_2 = acs_time("/input data/educ_input_data/S1401/Y8to14", starting.year = 2008)
data_3 = acs_time("/input data/educ_input_data/S1401/Y15", starting.year = 2015)

data = data %>% 
  select(enrolled_3_4 = Total..Estimate..Percent.of.age.group.enrolled.in.school......3.and.4.years,
         FIPS, year)
data_2 = data_2 %>% 
  select(enrolled_3_4 = Total..Estimate..Percent.of.age.group.enrolled.in.school......3.and.4.years,
         FIPS, year)
data_3 = data_3 %>% 
  select(enrolled_3_4 = Percent..Estimate..Population.3.to.4.years...3.to.4.year.olds.enrolled.in.school,
         FIPS, year)

enroll_3_4_data = rbind(data, data_2, data_3)



data = acs_time("/input data/educ_input_data/B15001")

data = data %>%
  mutate(num_m_25_34_assoc_plus = Estimate..Male....25.to.34.years....Associate.s.degree +
           Estimate..Male....25.to.34.years....Bachelor.s.degree +
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_assoc_plus = Estimate..Male....35.to.44.years....Associate.s.degree +
           Estimate..Male....35.to.44.years....Bachelor.s.degree +
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_assoc_plus = Estimate..Male....45.to.64.years....Associate.s.degree +
           Estimate..Male....45.to.64.years....Bachelor.s.degree +
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_assoc_plus = Estimate..Female....25.to.34.years....Associate.s.degree +
           Estimate..Female....25.to.34.years....Bachelor.s.degree +
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_assoc_plus = Estimate..Female....35.to.44.years....Associate.s.degree +
           Estimate..Female....35.to.44.years....Bachelor.s.degree +
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_assoc_plus = Estimate..Female....45.to.64.years....Associate.s.degree +
           Estimate..Female....45.to.64.years....Bachelor.s.degree +
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34_bach_plus = 
           Estimate..Male....25.to.34.years....Bachelor.s.degree +
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_bach_plus = 
           Estimate..Male....35.to.44.years....Bachelor.s.degree +
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_bach_plus = 
           Estimate..Male....45.to.64.years....Bachelor.s.degree +
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_bach_plus = 
           Estimate..Female....25.to.34.years....Bachelor.s.degree +
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_bach_plus = 
           Estimate..Female....35.to.44.years....Bachelor.s.degree +
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_bach_plus = 
           Estimate..Female....45.to.64.years....Bachelor.s.degree +
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34_grad = 
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_grad = 
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_grad = 
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_grad = 
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_grad = 
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_grad = 
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34 = Estimate..Male....25.to.34.years.,
         num_m_35_44 = Estimate..Male....35.to.44.years.,
         num_m_45_64 = Estimate..Male....45.to.64.years.,
         num_f_25_34 = Estimate..Female....25.to.34.years.,
         num_f_35_44 = Estimate..Female....35.to.44.years.,
         num_f_45_64 = Estimate..Female....45.to.64.years.,
         per_25_64_assoc_plus = (num_m_25_34_assoc_plus +
           num_m_35_44_assoc_plus + num_m_45_64_assoc_plus + num_f_25_34_assoc_plus +
           num_f_35_44_assoc_plus + num_f_45_64_assoc_plus)/
           (num_m_25_34 +
           num_m_35_44 + num_m_45_64 + num_f_25_34 +
           num_f_35_44 + num_f_45_64),
         per_25_64_bach_plus = (num_m_25_34_bach_plus +
            num_m_35_44_bach_plus + num_m_45_64_bach_plus + num_f_25_34_bach_plus +
            num_f_35_44_bach_plus + num_f_45_64_bach_plus)/
           (num_m_25_34 +
              num_m_35_44 + num_m_45_64 + num_f_25_34 +
              num_f_35_44 + num_f_45_64),
         per_25_64_grad = (num_m_25_34_grad +
            num_m_35_44_grad + num_m_45_64_bach_plus + num_f_25_34_grad +
            num_f_35_44_grad + num_f_45_64_grad)/
           (num_m_25_34 +
              num_m_35_44 + num_m_45_64 + num_f_25_34 +
              num_f_35_44 + num_f_45_64),
         per_25_34_assoc_plus = (num_f_25_34_assoc_plus+num_m_25_34_assoc_plus)/
           (num_m_25_34+num_f_25_34),
         per_25_34_bach_plus = (num_f_25_34_bach_plus+num_m_25_34_bach_plus)/
           (num_m_25_34+num_f_25_34),
         per_25_34_grad = (num_f_25_34_grad+num_m_25_34_grad)/
           (num_m_25_34+num_f_25_34)
         )

degree_data = data %>%
  select(FIPS, year, per_25_64_assoc_plus, per_25_64_bach_plus, per_25_64_grad,
         per_25_34_assoc_plus, per_25_34_bach_plus, per_25_34_grad)


degree_all_races = acs_time("/input data/educ_input_data/B15002")

degree_all_races = degree_all_races %>%
  mutate(bach_plus_per_all = (Estimate..Female....Bachelor.s.degree+
           Estimate..Male....Bachelor.s.degree +
           Estimate..Female....Doctorate.degree+
           Estimate..Male....Doctorate.degree +
           Estimate..Female....Master.s.degree +
           Estimate..Female....Master.s.degree)/
           Estimate..Total.)

degree_all_races = degree_all_races %>%
  select(FIPS, year, bach_plus_per_all)




degree_white_05 = acs_time("/input data/educ_input_data/B15002A/Y05", starting.year = 2005)
degree_white_08 = acs_time("/input data/educ_input_data/B15002A/Y08", starting.year = 2008)

degree_white_05 = degree_white_05 %>%
  mutate(bach_plus_per_white = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_white_05 = degree_white_05 %>%
  select(FIPS, year, bach_plus_per_white)

degree_white_08 = degree_white_08 %>%
  mutate(bach_plus_per_white = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_white_08 = degree_white_08 %>%
  select(FIPS, year, bach_plus_per_white)

degree_white = rbind(degree_white_05, degree_white_08)



degree_black_05 = acs_time("/input data/educ_input_data/B15002B/Y05", starting.year = 2005)
degree_black_08 = acs_time("/input data/educ_input_data/B15002B/Y08", starting.year = 2008)

degree_black_05 = degree_black_05 %>%
  mutate(bach_plus_per_black = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_black_05 = degree_black_05 %>%
  select(FIPS, year, bach_plus_per_black)

degree_black_08 = degree_black_08 %>%
  mutate(bach_plus_per_black = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_black_08 = degree_black_08 %>%
  select(FIPS, year, bach_plus_per_black)

degree_black = rbind(degree_black_05, degree_black_08)



degree_hispanic_05 = acs_time("/input data/educ_input_data/B15002I/Y05", starting.year = 2005)
degree_hispanic_08 = acs_time("/input data/educ_input_data/B15002I/Y08", starting.year = 2008)

degree_hispanic_05 = degree_hispanic_05 %>%
  mutate(bach_plus_per_hispanic = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_hispanic_05 = degree_hispanic_05 %>%
  select(FIPS, year, bach_plus_per_hispanic)

degree_hispanic_08 = degree_hispanic_08 %>%
  mutate(bach_plus_per_hispanic = (Estimate..Female....Bachelor.s.degree+
                                  Estimate..Male....Bachelor.s.degree +
                                  Estimate..Female....Graduate.degree+
                                  Estimate..Male....Graduate.degree )/
           Estimate..Total.)

degree_hispanic_08 = degree_hispanic_08 %>%
  select(FIPS, year, bach_plus_per_hispanic)

degree_hispanic = rbind(degree_hispanic_05, degree_hispanic_08)




occupation_05 = acs_time("/input data/educ_input_data/S2401/Y05", starting.year = 2005)
occupation_10 = acs_time("/input data/educ_input_data/S2401/Y10", starting.year = 2010)
occupation_15 = acs_time("/input data/educ_input_data/S2401/Y15", starting.year = 2015)

occupation_05 = occupation_05 %>%
  mutate(per_high_wage = (as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over...Management..professional..and.related.occupations.)+
           as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over...Service.occupations....Protective.service.occupations....Law.enforcement.workers.including.supervisors)+
           as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over...Construction..extraction..maintenance..and.repair.occupations....Installation..maintenance..and.repair.occupations))/
  as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over))

occupation_10 = occupation_10 %>%
  mutate(per_high_wage = (as.numeric(Total..Estimate..Management..business..science..and.arts.occupations.)+
                            as.numeric(Total..Estimate..Service.occupations....Protective.service.occupations....Law.enforcement.workers.including.supervisors)+
                            as.numeric(Total..Estimate..Natural.resources..construction..and.maintenance.occupations....Installation..maintenance..and.repair.occupations))/
           as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over))

occupation_15 = occupation_15 %>%
  mutate(per_high_wage = (as.numeric(Total..Estimate..Management..business..science..and.arts.occupations.)+
                            as.numeric(Total..Estimate..Service.occupations....Protective.service.occupations....Law.enforcement.workers.including.supervisors)+
                            as.numeric(Total..Estimate..Natural.resources..construction..and.maintenance.occupations....Installation..maintenance..and.repair.occupations))/
           as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over))

occupation_05 = occupation_05 %>% select(FIPS, year, per_high_wage)
occupation_10 = occupation_10 %>% select(FIPS, year, per_high_wage)
occupation_15 = occupation_15 %>% select(FIPS, year, per_high_wage)

occupation_data = rbind(occupation_05, occupation_10, occupation_15)
```

Merging the Data
```{r}
data = full_join(child_pov_data, degree_all_races, by = c("FIPS", "year"))
data = full_join(data, degree_black, by = c("FIPS", "year"))
data = full_join(data, degree_data, by = c("FIPS", "year"))
data = full_join(data, degree_hispanic, by = c("FIPS", "year"))
data = full_join(data, degree_white, by = c("FIPS", "year"))
data = full_join(data, enroll_3_4_data, by = c("FIPS", "year"))
# data = full_join(data, jcps_data, by = c("FIPS", "year"))
# data = full_join(data, naep_data, by = c("FIPS", "year"))
data = full_join(data, occupation_data, by = c("FIPS", "year"))
data$FIPS<-as.character(data$FIPS)
population_data <- read_csv("input data/population_data.csv", col_types = cols(FIPS = col_character()))
data = as.tibble(full_join(data, population_data, by = c("FIPS", "year")))
data$enrolled_3_4 = as.numeric(data$enrolled_3_4)/100


stl_data <- data %>%
  filter(FIPS == 29189 | FIPS == 29510) %>%
  group_by(year) %>%
  summarise_each(funs(weighted.mean(.,population)), -c(FIPS,population))
stl_data$FIPS <- "MERGED"

names = read_csv("input data/FIPS one stl.csv")

education_data <- data %>%
  filter(!(FIPS == 29189 | FIPS == 29510)) %>%
  bind_rows(stl_data) %>%
  left_join(names, by = "FIPS")
```


ACT and CCR Data for Kentucky
```{r}
ccr <- ccr_read("input data/educ_input_data/CCR_acc_data")
act<- act_read("input data/educ_input_data/ACT_data")

#CCR Scores


ccr_new <- ccr %>%
  filter((
    label == "All Students" |
      label == "Male" |
      label == "Female" |
      label == "White (Non-Hispanic)" |
      label == "African American" |
      label == "Hispanic" |
      label == "Asian"
  )
  )



#ACT Scores


act_new <- act %>%
  filter((
    label == "All Students" |
      label == "Male" |
      label == "Female" |
      label == "White (Non-Hispanic)" |
      label == "African American" |
      label == "Hispanic" |
      label == "Asian"
  )
  )

ky_new <-left_join(act_new, ccr_new, by = c("school_year","dist_name","SCH_NAME", "label"))
ky_new %<>%  mutate(year = as.numeric(substr(school_year,5,8)))%>%
  select(year,dist_name,label,num_students_tested:number_grads)


#Tidy this very untidy dataset - See recursively defined functions above.
ky_tidy_new <- restore_ky_ed_data(ky_new)
```


NAEP Data for Kentucky
```{r}
naep_math <- read_csv("input data/educ_input_data/naep_math_data.csv")
naep_reading <- read_csv("input data/educ_input_data/naep_reading_data.csv")

naep_reading %<>% select(Year, Jurisdiction, naep_reading_score = `Average scale score`, 
                         reading_sd = `Standard Error`)
naep_math %<>% select(Year, Jurisdiction, naep_math_score = `Average scale score`, 
                      math_sd = `Standard Error`)

naep_data <- left_join(naep_reading, naep_math, by = c("Year", "Jurisdiction"))
naep_data %<>% rename(year = Year)
```


Map Data
```{r}
data = read.csv("input data/educ_input_data/ACS_15_5YR_B17001_with_ann.csv", skip = 1)

data = data %>%
  mutate(under_5_per = (Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years+
                          Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years)/
           (Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....Under.5.years+
              Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....Under.5.years+
              Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years+
              Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years),
         five_to_17_under =  Estimate..Income.in.the.past.12.months.below.poverty.level....Male....5.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Male....6.to.11.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Male....12.to.14.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Male....15.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Male....16.and.17.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....5.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....6.to.11.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....12.to.14.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....15.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....16.and.17.years,
         five_to_17_over =  Estimate..Income.in.the.past.12.months.below.poverty.level....Male....5.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....6.to.11.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....12.to.14.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....15.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....16.and.17.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....5.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....6.to.11.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....12.to.14.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....15.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....16.and.17.years,
         five_to_17_per = five_to_17_under/(five_to_17_over+five_to_17_under),
         child_under = five_to_17_under +
           Estimate..Income.in.the.past.12.months.below.poverty.level....Male....Under.5.years+
           Estimate..Income.in.the.past.12.months.below.poverty.level....Female....Under.5.years,
         child_over = five_to_17_over +
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Male....Under.5.years+
           Estimate..Income.in.the.past.12.months.at.or.above.poverty.level....Female....Under.5.years,
         child_per = child_under/(child_over+child_under)
  )

child_pov_data = data %>% 
  select(Id, Geography, under_5_per, five_to_17_per, child_per)

data = read.csv("input data/educ_input_data/ACS_15_5YR_S1401_with_ann.csv", skip = 1)

enroll_data = data %>% 
  select(enrolled_3_4 = Percent..Estimate..Population.3.to.4.years...3.to.4.year.olds.enrolled.in.school,
         Id, Geography)

data = read.csv("input data/educ_input_data/ACS_15_5YR_B15001_with_ann.csv", skip = 1)

data = data %>%
  mutate(num_m_25_34_assoc_plus = Estimate..Male....25.to.34.years....Associate.s.degree +
           Estimate..Male....25.to.34.years....Bachelor.s.degree +
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_assoc_plus = Estimate..Male....35.to.44.years....Associate.s.degree +
           Estimate..Male....35.to.44.years....Bachelor.s.degree +
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_assoc_plus = Estimate..Male....45.to.64.years....Associate.s.degree +
           Estimate..Male....45.to.64.years....Bachelor.s.degree +
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_assoc_plus = Estimate..Female....25.to.34.years....Associate.s.degree +
           Estimate..Female....25.to.34.years....Bachelor.s.degree +
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_assoc_plus = Estimate..Female....35.to.44.years....Associate.s.degree +
           Estimate..Female....35.to.44.years....Bachelor.s.degree +
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_assoc_plus = Estimate..Female....45.to.64.years....Associate.s.degree +
           Estimate..Female....45.to.64.years....Bachelor.s.degree +
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34_bach_plus = 
           Estimate..Male....25.to.34.years....Bachelor.s.degree +
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_bach_plus = 
           Estimate..Male....35.to.44.years....Bachelor.s.degree +
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_bach_plus = 
           Estimate..Male....45.to.64.years....Bachelor.s.degree +
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_bach_plus = 
           Estimate..Female....25.to.34.years....Bachelor.s.degree +
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_bach_plus = 
           Estimate..Female....35.to.44.years....Bachelor.s.degree +
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_bach_plus = 
           Estimate..Female....45.to.64.years....Bachelor.s.degree +
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34_grad = 
           Estimate..Male....25.to.34.years....Graduate.or.professional.degree,
         num_m_35_44_grad = 
           Estimate..Male....35.to.44.years....Graduate.or.professional.degree,
         num_m_45_64_grad = 
           Estimate..Male....45.to.64.years....Graduate.or.professional.degree,
         num_f_25_34_grad = 
           Estimate..Female....25.to.34.years....Graduate.or.professional.degree,
         num_f_35_44_grad = 
           Estimate..Female....35.to.44.years....Graduate.or.professional.degree,
         num_f_45_64_grad = 
           Estimate..Female....45.to.64.years....Graduate.or.professional.degree,
         num_m_25_34 = Estimate..Male....25.to.34.years.,
         num_m_35_44 = Estimate..Male....35.to.44.years.,
         num_m_45_64 = Estimate..Male....45.to.64.years.,
         num_f_25_34 = Estimate..Female....25.to.34.years.,
         num_f_35_44 = Estimate..Female....35.to.44.years.,
         num_f_45_64 = Estimate..Female....45.to.64.years.,
         per_25_64_assoc_plus = (num_m_25_34_assoc_plus +
                                   num_m_35_44_assoc_plus + num_m_45_64_assoc_plus + num_f_25_34_assoc_plus +
                                   num_f_35_44_assoc_plus + num_f_45_64_assoc_plus)/
           (num_m_25_34 +
              num_m_35_44 + num_m_45_64 + num_f_25_34 +
              num_f_35_44 + num_f_45_64),
         per_25_64_bach_plus = (num_m_25_34_bach_plus +
                                  num_m_35_44_bach_plus + num_m_45_64_bach_plus + num_f_25_34_bach_plus +
                                  num_f_35_44_bach_plus + num_f_45_64_bach_plus)/
           (num_m_25_34 +
              num_m_35_44 + num_m_45_64 + num_f_25_34 +
              num_f_35_44 + num_f_45_64),
         per_25_64_grad = (num_m_25_34_grad +
                             num_m_35_44_grad + num_m_45_64_bach_plus + num_f_25_34_grad +
                             num_f_35_44_grad + num_f_45_64_grad)/
           (num_m_25_34 +
              num_m_35_44 + num_m_45_64 + num_f_25_34 +
              num_f_35_44 + num_f_45_64),
         per_25_34_assoc_plus = (num_f_25_34_assoc_plus+num_m_25_34_assoc_plus)/
           (num_m_25_34+num_f_25_34),
         per_25_34_bach_plus = (num_f_25_34_bach_plus+num_m_25_34_bach_plus)/
           (num_m_25_34+num_f_25_34),
         per_25_34_grad = (num_f_25_34_grad+num_m_25_34_grad)/
           (num_m_25_34+num_f_25_34)
  )

degree_data = data %>%
  select(Id, Id2, Geography, per_25_64_assoc_plus, per_25_64_bach_plus, per_25_64_grad,
         per_25_34_assoc_plus, per_25_34_bach_plus, per_25_34_grad)


data = read.csv("input data/educ_input_data/ACS_15_5YR_S2401_with_ann.csv", skip = 1)

data = data %>%
  mutate(per_high_wage = (as.numeric(Total..Estimate..Management..business..science..and.arts.occupations.)+
                            as.numeric(Total..Estimate..Service.occupations....Protective.service.occupations....Law.enforcement.workers.including.supervisors)+
                            as.numeric(Total..Estimate..Natural.resources..construction..and.maintenance.occupations....Installation..maintenance..and.repair.occupations))/
           as.numeric(Total..Estimate..Civilian.employed.population.16.years.and.over))

occupation_data = data %>% select(Id, Geography, per_high_wage)

name_data = read.csv("map data/census tract neighborhoods.csv")


map_data = full_join(child_pov_data, degree_data, by = c("Id", "Geography"))
map_data = full_join(map_data, enroll_data, by = c("Id", "Geography"))
map_data = full_join(map_data, occupation_data, by = c("Id", "Geography"))
map_data = full_join(map_data, name_data, by = "Id2")
```


```{r}
write_csv(ky_tidy_new, "output data/education_data_act_ccr.csv")
write_csv(naep_data, "output data/education_data_naep.csv")
write_csv(education_data, "output data/education_data_fips.csv")
write_csv(map_data, "output data/education_map_data.csv")
```














