---
title: "Jobs Graphing"
output: html_notebook
---

Code for the graphs appearing in the Jobs section of the GLP website.

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/natek/Documents/GitHub/glp_website"))
```


Loading libraries
```{r}
library(showtext)
library(reshape2)
library(classInt)
library(ggthemes)
library(tidyverse)
library(rgdal)
library(leaflet)
library(RColorBrewer)
library(htmlwidgets)
```

Reading in data
```{r}
jobs_data_fips <- read_csv("output data/jobs_data_fips.csv")
jobs_data_msa <- read_csv("output data/jobs_data_msa.csv")
```


Reading in graphing functions and font
```{r}
source("graphing_functions.R")

font.add("Museo Sans 300", "/Users/BryceRowland/Desktop/GLP/R Code/MuseoSans_300.otf")
font.add("Museo Sans 300 Italic", "/Users/BryceRowland/Desktop/GLP/R Code/MuseoSans_300_Italic.otf")
```

Adding Map Data
```{r}
setwd("~/Desktop/glp_website/map data")
map_data = read_csv("jobs_map_data.csv")

map_data$unemp_pct = map_data$unemp_pct*100

map_jc = readOGR("JC Tracts", layer = "JC Tracts",
                 GDAL1_integer64_policy = TRUE)

map_jc@data<-full_join(map_jc@data, map_data, by = c('GEO_ID' = 'Id'))

map_jc@data$tract_num <- substr(map_jc@data$Id2, 6, 11)

map_jc@data$l_line1 <- paste("Tract #:", map_jc@data$tract_num, "in the")
map_jc@data$l_line2 <- paste(map_jc@data$Neighborhood, "neighborhood")
```

Trendline Graphs
```{r}
setwd("~/Desktop/glp_website/Images/Jobs Images")


##trendlines

jpeg("jobs_earnings_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(jobs_data_fips, "median_earnings",
                plot_title = "Median Earnings",
                subtitle = "",
                rollmean = 1,
                caption_text = "Source: Greater Louisville Project \nData from the American Community Survey, Table S2001",
                xmin = 2005, xmax = 2015, y_title = "Dollars")
showtext.end()
dev.off()


jpeg("jobs_income_inequality_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(jobs_data_fips, "income_inequality",
                plot_title = "Income Inequality",
                subtitle = "Mean income of top quintile divided by mean income of bottom quintile",
                rollmean = 1,
                caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED",
                xmin = 2010, xmax = 2015, y_title = "Ratio")
showtext.end()
dev.off()

jpeg("jobs_median_household_income_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(jobs_data_fips, "median_household_income",
                plot_title = "Median Household Income",
                subtitle = "Annual",
                rollmean = 1,
                caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED",
                xmin = 2005, xmax = 2014, y_title = "Dollars")
showtext.end()
dev.off()


jpeg("jobs_personal_income_per_cap_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(jobs_data_fips, "personal_income_per_cap",
                plot_title = "Per Capita Personal Income",
                subtitle = "Annual",
                rollmean = 1,
                caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED",
                xmin = 2005, xmax = 2015, y_title = "Dollars")
showtext.end()
dev.off()


jpeg("jobs_unemployment_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(jobs_data_fips, "unemployment",
                plot_title = "Unemployment",
                caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED",
                subtitle = "Annual",
                rollmean = 1,
                xmin = 2005, xmax = 2015)
showtext.end()
dev.off()

jpeg("jobs_estabs_entry_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'estabs_entry_rate',
                       plot_title = "Establishment Entry Rate",
                       subtitle = "3-year rolling average",
                       rollmean = 3,
                       caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                       xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_job_creation_rate_births_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'job_creation_rate_births',
                    plot_title = "Job Creation Birth Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_job_destruction_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'job_destruction_rate',
                    plot_title = "Job Destruction Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_job_destruction_rate_deaths_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'job_destruction_rate_deaths',
                    plot_title = "Job Destruction Death Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_estabs_exit_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'estabs_exit_rate',
                    plot_title = "Establishment Exit Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_job_creation_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'job_creation_rate',
                    plot_title = "Job Creation Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_net_est_entry_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'estabs_entry_rate_minus_exit',
                    plot_title = "Net Establishment Entry Rate",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()

jpeg("jobs_net_job_creation_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(jobs_data_msa, 'net_job_creation_rate',
                    plot_title = "Net Job Creation Rate",
                    subtitle = "3-year rolling average",
                    rollmean = 3,
                    caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS",
                    xmin = 2003, xmax = 2014)
showtext.end()
dev.off()


```

Rankings graphs

```{r}
dat_15 <- jobs_data_fips %>% filter(year == 2015)
dat_14 <- jobs_data_fips %>% filter(year == 2014)

font.add("Museo Sans 300", "C:/Users/natek/Documents/fonts/MuseoSans/MuseoSans_300.otf")
font.add("Museo Sans Italic", "C:/Users/natek/Documents/fonts/MuseoSans/MuseoSans_300_Italic.otf")

setwd("~/Desktop/glp_website/Images/Jobs Images")

jpeg("jobs_earnings_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(dat_15, "median_earnings", order = "Descending",
                  plot_title = "Median Earnings, 2015", 
                  y_title = "Dollars",
                  caption_text = "Source: Greater Louisville Project \nData from the American Community Survey Table S2001")
showtext.end()
dev.off()

jpeg("jobs_income_inequality_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(dat_15, "income_inequality", order = "Ascending",
                  plot_title = "Income Inequality, 2015", 
                  y_title = "Ratio",
                  caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED")
showtext.end()
dev.off()

jpeg("jobs_median_household_income_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(dat_14, "median_household_income", order = "Descending",
                  plot_title = "Median Household Income, 2015", 
                  y_title = "Dollars",
                  caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED")
showtext.end()
dev.off()


jpeg("jobs_personal_income_per_cap_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(dat_15, "personal_income_per_cap", order = "Descending",
                  plot_title = "Per Capita Personal Income, 2015", 
                  y_title = "Dollars",
                  caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED")
showtext.end()
dev.off()

jpeg("jobs_unemployment_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(dat_15, "unemployment", order = "Ascending",
                  plot_title = "Unemployment, 2015", 
                  caption_text = "Source: Greater Louisville Project \nData from the Federal Reserve via GeoFRED")
showtext.end()
dev.off()

jpeg("jobs_estabs_entry_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'estabs_entry_rate',
                  order = "Descending",
                  plot_title = "Establishment Entry Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_estabs_exit_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'estabs_exit_rate',
                  order = "Ascending",
                  plot_title = "Establishment Exit Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_job_creation_rate_births_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'job_creation_rate_births',
                  order = "Descending",
                  plot_title = "Jobs Creation Birth Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_job_creation_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'job_creation_rate',
                  order = "Descending",
                  plot_title = "Job Creation Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_job_destruction_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'job_destruction_rate',
                  order = "Ascending",
                  plot_title = "Job Destruction Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_job_destruction_rate_deaths_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'job_destruction_rate_deaths',
                  order = "Ascending",
                  plot_title = "Job Destruction Death Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_job_creation_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'job_creation_rate',
                  order = "Descending",
                  plot_title = "Job Creation Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_net_est_entry_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'estabs_entry_rate_minus_exit',
                  order = "Descending",
                  plot_title = "Net Establishment Entry Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

jpeg("jobs_net_job_creation_rate_ranking.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(filter(jobs_data_msa, year == 2014), 'net_job_creation_rate',
                  order = "Descending",
                  plot_title = "Net Job Creation Rate, 2014",
                  caption_text = "Source: Greater Louisville Project \nData from United States Census Bureau, BDS")
showtext.end()
dev.off()

```


Mapping
Reading in data for mapping
```{r}

jobs_map_data = read_csv("map data/jobs_map_data.csv")

map_jc = readOGR("map data/JC Tracts", layer = "JC Tracts",
                 GDAL1_integer64_policy = TRUE)

map_jc@data<-full_join(map_jc@data, jobs_map_data, by = c('GEO_ID' = 'Id'))

map_jc@data$tract_num <- substr(map_jc@data$Id2, 6, 11)

map_jc@data$l_line1 <- paste("Tract #:", map_jc@data$tract_num, "in the")
map_jc@data$l_line2 <- paste(map_jc@data$Neighborhood, "neighborhood")


```


Making and saving maps
```{r}
setwd("~/Desktop/glp_website/Images/Maps/jobs_maps")

m <- make_map("unemp_pct", "Unemployment", legend_title = "Unemployment<br/>")
saveWidget(m, "jobs_unemp_map.html")

m <- make_map(
  "median_household_income",
  "Median Household Income",
  legend_title = "Median<br/>Household<br/>Income",
  units = "Dollars",
  map_style = "Divergent"
  )
saveWidget(m, "jobs_median_household_income_map.html")

m <- make_map(
  "median_earnings",
  "Median Earnings",
  legend_title = "Median<br/>Earnings<br/>",
  units = "Dollars",
  map_style = "Divergent"
  )
saveWidget(m, "jobs_median_earnings_map.html")
```

