---
title: "Jobs Data Pull"
output: html_notebook
---

This is the code used to pull the jobs data


First the libraries needed
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/glp_website"))
# knitr::opts_knit$set(root.dir = normalizePath("C:/Users/natek/Documents/GitHub/glp_website"))
```


```{r libraries, message = FALSE}
library(tidyverse)
library(magrittr)
```


This function takes a folder of ACS data with a separate CSV for each year, because that is what is downloaded from FactFinder. 
```{r acs folder function}
acs_time <- function(folder, starting.year=2005){
  wd <- getwd()
  directory <- paste(wd, folder, sep = "")
  file_names <- list.files(directory)
  n<-length(file_names)
  y<-starting.year
  for (i in 1:n){
    file_path <- paste(wd, folder, file_names[i], sep = "")
    data<-read_csv(file_path, skip=1, col_types = cols("Id2" = col_double()))
    names(data)[names(data) == 'Id2'] <- 'FIPS'
    all.peers <-subset(data, data$FIPS == 1073 |data$FIPS == 37119
                       |data$FIPS == 39061 |data$FIPS == 39049
                       |data$FIPS == 26081 |data$FIPS == 37081
                       |data$FIPS == 45045 |data$FIPS == 18097
                       |data$FIPS == 29095 |data$FIPS == 47093
                       |data$FIPS == 21111 |data$FIPS == 47157
                       |data$FIPS == 47037 |data$FIPS == 40109
                       |data$FIPS == 31055 |data$FIPS == 29189
                       |data$FIPS == 29510
                       |data$FIPS == 40143 |data$FIPS == 39113
                       |data$FIPS == 12031 |data$FIPS == 37183
                       |data$FIPS == 51760)
    
    all.peers$year<-y
    y<-y+1
    
    if(i==1){
     df<-all.peers 
    }
    else{
      names(all.peers)<-names(df)
      df<-rbind(df, all.peers)
    }
  }
  df
}
```

pull peers FIPS to use with GeoFRED data
```{r}
pull_peers_FIPS <- function(dat){
  all.peers <- subset(dat, dat$FIPS == 1073 | dat$FIPS == 37119
                    |dat$FIPS == 39061 |dat$FIPS == 39049
                    |dat$FIPS == 26081 |dat$FIPS == 37081
                    |dat$FIPS == 45045 |dat$FIPS == 18097
                    |dat$FIPS == 29095 |dat$FIPS == 47093
                    |dat$FIPS == 21111 |dat$FIPS == 47157
                    |dat$FIPS == 47037 |dat$FIPS == 40109
                    |dat$FIPS == 31055 |dat$FIPS == 29189
                    |dat$FIPS == 29510 |dat$FIPS == 40143
                    |dat$FIPS == 12031 |dat$FIPS == 37183
                    |dat$FIPS == 39113 |dat$FIPS == 51760
                    | dat$FIPS == "01073")
  all.peers$baseline <- 1
  all.peers$current <- 1
  all.peers$baseline[all.peers$FIPS==26081|all.peers$FIPS==29189
                     |all.peers$FIPS==29510|all.peers$FIPS==40109
                     |all.peers$FIPS==40143|all.peers$FIPS==45045
                     |all.peers$FIPS==47093]<-0
  all.peers$current[all.peers$FIPS== 12031|all.peers$FIPS==37183|
                      all.peers$FIPS==39113|all.peers$FIPS==51760]<-0
  all.peers
}
```

```{r}
pull_peers_MSA<-function(data){
  all.peers<-filter(data, data$MSA == 24340 | data$MSA == 41180
                    |data$MSA == 36420 | data$MSA == 46140
                    |data$MSA == 24860 |data$MSA == 28940
                    |data$MSA == 13820 |data$MSA == 26900
                    |data$MSA == 31140 |data$MSA == 28140
                    |data$MSA == 36540 |data$MSA == 24660
                    |data$MSA == 16740 |data$MSA == 18140
                    |data$MSA == 17140 |data$MSA == 34980
                    |data$MSA == 32820 |data$MSA == 27260
                    |data$MSA == 39580 |data$MSA == 19380
                    |data$MSA == 40060)
  all.peers$baseline<-1
  all.peers$current<-1
  all.peers$baseline[all.peers$MSA == 24340 | all.peers$MSA == 41180
                     |all.peers$MSA == 36420 | all.peers$MSA == 46140
                     |all.peers$MSA == 24860 | all.peers$MSA == 28940]<-0
  all.peers$current[all.peers$MSA == 27260 | all.peers$MSA == 39580
                    |all.peers$MSA == 19380 | all.peers$MSA == 40060]<-0
  all.peers
}
```


Earnings data from the ACS 
```{r, message = FALSE}
earn_data <- acs_time("/input data/jobs_input_data/S2001/")

earn_data<-select(earn_data, FIPS, year, earnings = `Total; Estimate; Population 16 years and over with earnings - Median earnings (dollars)`)
earn_data$num_earnings = as.numeric(as.character(earn_data$earnings))
earn_data$FIPS <- as.character(earn_data$FIPS)
```

Other jobs data from GeoFRED
```{r geofred}
##reading in the data
unemp_dat <- read_csv("input data/jobs_input_data/GeoFRED_unemployment.csv", skip = 1)
income_inequality_dat <- read_csv("input data/jobs_input_data/income_inequality.csv", skip = 1)
median_household_income_dat <- read_csv("input data/jobs_input_data/median_household_income.csv", skip = 1)
personal_income_per_cap_dat <- read_csv("input data/jobs_input_data/per capita personal income.csv", skip = 1)

##pulling peers
#renaming
unemp_dat <- unemp_dat %>% rename(FIPS = `Region Code`)
income_inequality_dat <- income_inequality_dat %>% rename(FIPS = `Region Code`)
median_household_income_dat <- median_household_income_dat %>% rename(FIPS = `Region Code`)
personal_income_per_cap_dat <- personal_income_per_cap_dat %>% rename(FIPS = `Region Code`)

#pulling
unemp_dat <- pull_peers_FIPS(unemp_dat)
income_inequality_dat <- pull_peers_FIPS(income_inequality_dat)
median_household_income_dat <- pull_peers_FIPS(median_household_income_dat)
personal_income_per_cap_dat <- pull_peers_FIPS(personal_income_per_cap_dat)

##reformatting
unemp_dat <- unemp_dat %>%
  gather(4:24, key = "year", value = "unemployment") #4:224 refers to column indexes for all the years

income_inequality_dat <- income_inequality_dat %>%
  gather(4:9, key = "year", value = "income_inequality") #4:224 refers to column indexes for all the years

median_household_income_dat <- median_household_income_dat %>%
  gather(4:24, key = "year", value = "median_household_income") #4:224 refers to column indexes for all the years

personal_income_per_cap_dat <- personal_income_per_cap_dat %>%
  gather(4:24, key = "year", value = "personal_income_per_cap") #4:224 refers to column indexes for all the years

dat <- full_join(unemp_dat, income_inequality_dat, by = c("FIPS", "year"))
dat <- full_join(dat, median_household_income_dat, by = c("FIPS", "year"))
dat <- full_join(dat, personal_income_per_cap_dat, by = c("FIPS", "year"))
dat$FIPS[dat$FIPS == "01073"] = "1073"
earn_data$year <- as.character(earn_data$year)
dat <- full_join(dat, earn_data, by = c("FIPS", "year")) #joining with earning data
dat <- dat %>% select(FIPS, year, median_earnings = num_earnings, income_inequality, median_household_income, 
                      personal_income_per_cap, unemployment)
```


```{r}

#current peers
dat$year <- as.numeric(dat$year)
dat$median_household_income <- as.numeric(dat$median_household_income)


##Now to give the FIPS codes names
names <- read_csv("input data/FIPS two stl.csv")

names$FIPS <- as.character(names$FIPS)
data_named <- left_join(dat, names, by = "FIPS")

##add population data
population_data <- read_csv("input data/population_data.csv")
population_data$FIPS <- as.character(population_data$FIPS)
data_named$year <- as.numeric(data_named$year)
data_named <- left_join(data_named, population_data, by = c("FIPS", "year"))

##and merge St. Louis city and St. Louis county

data_named$FIPS <- as.numeric(data_named$FIPS)
dat <- data_named %>%
  filter(year > 2004 & year < 2016) %>%
  select(-county, -state) %>%
  group_by(city, year) %>%
  summarise_each(funs(weighted.mean(.,population)), -population) %>%
  ungroup()

# give St. Louis Merged a new FIPS
dat$FIPS <- as.character(dat$FIPS)
dat$FIPS[dat$city == "St. Louis"] <- "MERGED"
dat$FIPS <- as.factor(dat$FIPS)

# and then add the other stuff for each city again
names <- read_csv("input data/FIPS one stl.csv")
names$FIPS <- as.factor(names$FIPS)

dat <- left_join(dat, names, by = c("FIPS", "city"))

population_data<-read_csv("input data/population_data_one_stl.csv", 
                          col_types = cols(FIPS = col_character()))
dat <- left_join(dat, population_data, by = c("FIPS", "year"))
# dat %<>% rename(current = current_peer, baseline = baseline_peer)
```


```{r}
bds_data = read_csv("input data/jobs_input_data/bds_f_msa_release.csv")
# bds_data = rename(bds_data, MSA = msa)

bds_data = bds_data %>%
  rename(MSA = msa, year = year2)%>%
  pull_peers_MSA(.)

bds_data = bds_data[bds_data$year >= 2003,]
bds_data$city<-NA
bds_data$city[bds_data$MSA == 24340] = "Grand Rapids"
bds_data$city[bds_data$MSA == 41180] = "St. Louis"
bds_data$city[bds_data$MSA == 36420] = "Oklahoma City"
bds_data$city[bds_data$MSA == 46140] = "Tulsa"
bds_data$city[bds_data$MSA == 24860] = "Greenville"
bds_data$city[bds_data$MSA == 28940] = "Knoxville"
bds_data$city[bds_data$MSA == 13820] = "Birmingham"
bds_data$city[bds_data$MSA == 31140] = "Louisville"
bds_data$city[bds_data$MSA == 26900] = "Indianapolis"
bds_data$city[bds_data$MSA == 28140] = "Kansas City"
bds_data$city[bds_data$MSA == 36540] = "Omaha"
bds_data$city[bds_data$MSA == 24660] = "Greensboro"
bds_data$city[bds_data$MSA == 16740] = "Charlotte"
bds_data$city[bds_data$MSA == 18140] = "Columbus"
bds_data$city[bds_data$MSA == 17140] = "Cincinnati"
bds_data$city[bds_data$MSA == 34980] = "Nashville"
bds_data$city[bds_data$MSA == 32820] = "Memphis"
bds_data$city[bds_data$MSA == 27260] = "Jacksonville"
bds_data$city[bds_data$MSA == 39580] = "Raleigh"
bds_data$city[bds_data$MSA == 19380] = "Dayton"
bds_data$city[bds_data$MSA == 40060] = "Richmond"

bds_data<-mutate(bds_data, estabs_entry_rate_minus_exit = estabs_entry_rate -estabs_exit_rate)
```

Creating Map Data
```{r}
unemp <- read_csv("input data/jobs_input_data/ACS_15_5YR_B23025_with_ann.csv", skip = 1,
                  col_types = cols(Id2 = col_character(),
                                   Id = col_character()))

unemp %<>% select(Id, Id2, pop = `Estimate; In labor force: - Civilian labor force:`,
                  unemp = `Estimate; In labor force: - Civilian labor force: - Unemployed`)%>%
  transmute(unemp_pct = unemp/pop, Id, Id2)%>%
  mutate(FIPS = as.character(substr(Id2, 1,5)))%>%
  filter(FIPS == "21111")

neighborhoods <- read_csv("~/Desktop/glp_website/map data/census tract neighborhoods.csv",col_types = cols(Id2 = col_character()))

jobs_map_data<- left_join(unemp, neighborhoods, by = "Id2")
```


Writing out data
```{r}
write_csv(dat, "output data/jobs_data_fips.csv")
write_csv(bds_data, "output data/jobs_data_msa.csv")
write_csv(jobs_map_data, "map data/jobs_map_data.csv")
```