---
title: "QOP_pull"
output: html_notebook
---

Code for pulling quality of place data


Nate Code
```{r}
library(showtext)
library(reshape2)
library(classInt)
library(ggthemes)
library(tidyverse)

setwd("C:/Users/natek/Documents/GeoFRED data/")
dat <- read_csv("GeoFRED_unemployment.csv", skip = 1)
dat <- dat %>% rename(FIPS = `Region Code`)


pull_peers_FIPS <- function(dat){
  all.peers <- subset(dat, dat$FIPS == 1073 | dat$FIPS == 37119
                    |dat$FIPS == 39061 |dat$FIPS == 39049
                    |dat$FIPS == 26081 |dat$FIPS == 37081
                    |dat$FIPS == 45045 |dat$FIPS == 18097
                    |dat$FIPS == 29095 |dat$FIPS == 47093
                    |dat$FIPS == 21111 |dat$FIPS == 47157
                    |dat$FIPS == 47037 |dat$FIPS == 40109
                    |dat$FIPS == 31055 |dat$FIPS == 29189
                    |dat$FIPS == 29510 |dat$FIPS == 40143
                    |dat$FIPS == 12031 |dat$FIPS == 37183
                    |dat$FIPS == 39113 |dat$FIPS == 51760)
  all.peers$baseline <- 1
  all.peers$current <- 1
  all.peers$baseline[all.peers$FIPS==26081|all.peers$FIPS==29189
                     |all.peers$FIPS==29510|all.peers$FIPS==40109
                     |all.peers$FIPS==40143|all.peers$FIPS==45045
                     |all.peers$FIPS==47093]<-0
  all.peers$current[all.peers$FIPS== 12031|all.peers$FIPS==37183|
                      all.peers$FIPS==39113|all.peers$FIPS==51760]<-0
  all.peers
}

dat <- pull_peers_FIPS(dat)

unemp_dat <- dat %>%
  gather(4:24, key = "year", value = "unemployment") #4:224 refers to column indexes for all the years


##all the other geofred data

house_dat <- read_csv("all_transactions_house_price_index.csv", skip = 1)
burdened_dat <- read_csv("burdened_households.csv", skip = 1)
disconnected_dat <- read_csv("disconnected youth.csv", skip = 1)
home_own_dat <- read_csv("homeownership_rate.csv", skip = 1)
income_inequality_dat <- read_csv("income_inequality.csv", skip = 1)
commute_time_dat <- read_csv("mean_commuting_time.csv", skip = 1)
median_household_income_dat <- read_csv("median_household_income.csv", skip = 1)
net_migration_flow_dat <- read_csv("net_migration_flow.csv", skip = 1)
personal_income_per_cap_dat <- read_csv("per capita personal income.csv", skip = 1)
race_dat <- read_csv("white to nonwhite racial dissimilarity index.csv", skip = 1)

##pulling peers

#renaming
house_dat <- house_dat %>% rename(FIPS = `Region Code`)
burdened_dat <- burdened_dat %>% rename(FIPS = `Region Code`)
disconnected_dat <- disconnected_dat %>% rename(FIPS = `Region Code`)
home_own_dat <- home_own_dat %>% rename(FIPS = `Region Code`)
income_inequality_dat <- income_inequality_dat %>% rename(FIPS = `Region Code`)
commute_time_dat <- commute_time_dat %>% rename(FIPS = `Region Code`)
median_household_income_dat <- median_household_income_dat %>% rename(FIPS = `Region Code`)
net_migration_flow_dat <- net_migration_flow_dat %>% rename(FIPS = `Region Code`)
personal_income_per_cap_dat <- personal_income_per_cap_dat %>% rename(FIPS = `Region Code`)
race_dat <- race_dat %>% rename(FIPS = `Region Code`)

#pulling

house_dat <- pull_peers_FIPS(house_dat)
burdened_dat <- pull_peers_FIPS(burdened_dat)
disconnected_dat <- pull_peers_FIPS(disconnected_dat)
home_own_dat <- pull_peers_FIPS(home_own_dat)
income_inequality_dat <- pull_peers_FIPS(income_inequality_dat)
commute_time_dat <- pull_peers_FIPS(commute_time_dat)
median_household_income_dat <- pull_peers_FIPS(median_household_income_dat)
net_migration_flow_dat <- pull_peers_FIPS(net_migration_flow_dat)
personal_income_per_cap_dat <- pull_peers_FIPS(personal_income_per_cap_dat)
race_dat <- pull_peers_FIPS(race_dat)




##reformatting
house_dat <- house_dat %>%
  gather(4:24, key = "year", value = "housing_price_index") #4:224 refers to column indexes for all the years

burdened_dat <- burdened_dat %>%
  gather(4:9, key = "year", value = "burdened_households") #4:224 refers to column indexes for all the years

disconnected_dat <- disconnected_dat %>%
  gather(4:10, key = "year", value = "disconnected_youth") #4:224 refers to column indexes for all the years

home_own_dat <- home_own_dat %>%
  gather(4:10, key = "year", value = "home_ownership") #4:224 refers to column indexes for all the years

income_inequality_dat <- income_inequality_dat %>%
  gather(4:9, key = "year", value = "income_inequality") #4:224 refers to column indexes for all the years

commute_time_dat <- commute_time_dat %>%
  gather(4:10, key = "year", value = "commute_time") #4:224 refers to column indexes for all the years

median_household_income_dat <- median_household_income_dat %>%
  gather(4:24, key = "year", value = "median_household_income") #4:224 refers to column indexes for all the years

net_migration_flow_dat <- net_migration_flow_dat %>%
  gather(4:8, key = "year", value = "net_migration_flow") #4:224 refers to column indexes for all the years

personal_income_per_cap_dat <- personal_income_per_cap_dat %>%
  gather(4:24, key = "year", value = "personal_income_per_cap") #4:224 refers to column indexes for all the years

race_dat <- race_dat %>%
  gather(4:10, key = "year", value = "racial_geography") #4:224 refers to column indexes for all the years


fred_dat <- full_join(burdened_dat, commute_time_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, disconnected_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, home_own_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, house_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, income_inequality_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, median_household_income_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, net_migration_flow_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, personal_income_per_cap_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, race_dat, by = c("FIPS", "year"))
fred_dat <- full_join(fred_dat, unemp_dat, by = c("FIPS", "year"))

fred_dat <- fred_dat %>% select(FIPS, year, baseline, current, 
                                burdened_households, commute_time, disconnected_youth,
                                home_ownership, housing_price_index, income_inequality, 
                                median_household_income, net_migration_flow, personal_income_per_cap,
                                racial_geography, unemployment)


#current peers
fred_dat$year <- as.numeric(fred_dat$year)
fred_dat$housing_price_index <- as.numeric(fred_dat$housing_price_index)
fred_dat$median_household_income <- as.numeric(fred_dat$median_household_income)
fred_dat$racial_geography <- as.numeric(fred_dat$racial_geography)


#
##Now to give the FIPS codes names
names <- read_csv("C:/Users/natek/Dropbox/GLP/FIPS two stl.csv")

names$FIPS <- as.character(names$FIPS)
data_named <- left_join(fred_dat, names, by = "FIPS")

##add population data
population_data <- read_csv("C:/users/natek/Documents/Github/glp_website/input data/population_data.csv")
population_data$FIPS <- as.character(population_data$FIPS)
data_named$year <- as.numeric(data_named$year)
data_named <- left_join(data_named, population_data, by = c("FIPS", "year"))

##and merge St. Louis city and St. Louis county

data_named$FIPS <- as.numeric(data_named$FIPS)
dat <- data_named %>%
  filter(year > 2004 & year < 2016) %>%
  select(-county, -state) %>%
  group_by(city, year) %>%
  summarise_each(funs(weighted.mean(.,population)), -population) %>%
  ungroup()

# give St. Louis Merged a new FIPS
dat$FIPS <- as.character(dat$FIPS)
dat$FIPS[dat$city == "St. Louis"] <- "MERGED"
dat$FIPS <- as.factor(dat$FIPS)

# and then add the other stuff for each city again
names <- read_csv("C:/users/natek/Dropbox/GLP/FIPS one stl.csv")
names$FIPS <- as.factor(names$FIPS)

fred_dat <- left_join(dat, names, by = c("FIPS", "city"))

population_data$FIPS <- as.character(population_data$FIPS)
fred_dat <- left_join(fred_dat, population_data, by = c("FIPS", "year"))


fred_dat <- fred_dat %>% 
  group_by(city, year) %>%
  mutate(population = sum(population)) %>%
  ungroup()

fred_dat <- fred_dat %>% 
  mutate(migration_pop = net_migration_flow/population)

write_csv(fred_dat, "GeoFRED data processed.csv")
```

Bryce Code
```{r}
#Quality of Place Upload for GLP website refresh
library(tidyverse)
library(magrittr)

setwd("~/Desktop/glp_website")

#####################################################################################
#Necessary Functions
#####################################################################################

pull_peers_MSA<-function(data){
  all.peers<-filter(data, data$CBSA == 24340 | data$CBSA == 41180
                    |data$CBSA == 36420 | data$CBSA == 46140
                    |data$CBSA == 24860 |data$CBSA == 28940
                    |data$CBSA == 13820 |data$CBSA == 26900
                    |data$CBSA == 31140 |data$CBSA == 28140
                    |data$CBSA == 36540 |data$CBSA == 24660
                    |data$CBSA == 16740 |data$CBSA == 18140
                    |data$CBSA == 17140 |data$CBSA == 34980
                    |data$CBSA == 32820 |data$CBSA == 27260
                    |data$CBSA == 39580 |data$CBSA == 19380
                    |data$CBSA == 40060)
  all.peers$baseline<-1
  all.peers$current<-1
  all.peers$baseline[all.peers$CBSA == 24340 | all.peers$CBSA == 41180
                     |all.peers$CBSA == 36420 | all.peers$CBSA == 46140
                     |all.peers$CBSA == 24860 | all.peers$CBSA == 28940]<-0
  all.peers$current[all.peers$CBSA == 27260 | all.peers$CBSA == 39580
                    |all.peers$CBSA == 19380 | all.peers$CBSA == 40060]<-0
  all.peers
}

pull_peers_FIPS <- function(dat){
  all.peers <- subset(dat, dat$FIPS == 1073 | dat$FIPS == 37119
                      |dat$FIPS == 39061 |dat$FIPS == 39049
                      |dat$FIPS == 26081 |dat$FIPS == 37081
                      |dat$FIPS == 45045 |dat$FIPS == 18097
                      |dat$FIPS == 29095 |dat$FIPS == 47093
                      |dat$FIPS == 21111 |dat$FIPS == 47157
                      |dat$FIPS == 47037 |dat$FIPS == 40109
                      |dat$FIPS == 31055 |dat$FIPS == 29189
                      |dat$FIPS == 29510 |dat$FIPS == 40143
                      |dat$FIPS == 12031 |dat$FIPS == 37183
                      |dat$FIPS == 39113 |dat$FIPS == 51760
                      |dat$FIPS == 0 | dat$FIPS == "01073")
  all.peers$baseline <- 1
  all.peers$current <- 1
  all.peers$baseline[all.peers$FIPS==26081|all.peers$FIPS==29189
                     |all.peers$FIPS==29510|all.peers$FIPS==40109
                     |all.peers$FIPS==40143|all.peers$FIPS==45045
                     |all.peers$FIPS==47093]<-0
  all.peers$current[all.peers$FIPS== 12031|all.peers$FIPS==37183|
                      all.peers$FIPS==39113|all.peers$FIPS==51760]<-0
  all.peers
}

cbp_read<-function(folder, starting_year){
  initial_wd <- getwd()
  directory <- paste(initial_wd, folder, sep = "/")
  setwd(directory)
  file_names<-list.files()
  n <- length(file_names)
  y <- starting_year
  for(i in 1:n){
    data<-read_csv(file_names[i], skip = 0)
    data%<>%mutate(FIPS = paste(fipstate, fipscty, sep = ''))
    all.peers <- filter(data, data$FIPS == "01073" |data$FIPS == 37119
                        |data$FIPS == 39061 |data$FIPS == 39049
                        |data$FIPS == 26081 |data$FIPS == 37081
                        |data$FIPS == 45045 |data$FIPS == 18097
                        |data$FIPS == 29095 |data$FIPS == 47093
                        |data$FIPS == 21111 |data$FIPS == 47157
                        |data$FIPS == 47037 |data$FIPS == 40109
                        |data$FIPS == 31055 |data$FIPS == 29189
                        |data$FIPS == 29510
                        |data$FIPS == 40143 |data$FIPS == 39113
                        |data$FIPS == 12031 |data$FIPS == 37183
                        |data$FIPS == 37183 |data$FIPS == 51760)
    all.peers$year <- y
    all.peers$baseline <- 1
    all.peers$current <- 1
    all.peers$baseline[all.peers$FIPS==26081|all.peers$FIPS==29189
                       |all.peers$FIPS==29510|all.peers$FIPS==40109
                       |all.peers$FIPS==40143|all.peers$FIPS==45045
                       |all.peers$FIPS==47093]<-0
    all.peers$current[all.peers$FIPS== 12031|all.peers$FIPS==37183|
                        all.peers$FIPS==39113|all.peers$FIPS==51760]<-0
    y<-y+1
    
    if(i == 1){
      df <- all.peers
    }
    else{
      names(all.peers)<-names(df)
      df<-rbind(df, all.peers)
    }
  }
  setwd(initial_wd)
  df
}

volunteer_read<-function(data){
  df<-read_csv(data)
  colnames(df)<-c("RANK", "CITY","STATE","volunteer_pct")
  year = substr(data, 57, 60)
  df$Year = NA
  df$Year = as.numeric(year)
  df%<>%filter(CITY == "Birmingham" | CITY == "Charlotte"|
                 CITY == "Cincinnati" | CITY == "Columbus" |
                 CITY == "Greensboro" | CITY == "Grand Rapids" |
                 CITY == "Greenville" | CITY == "Indianapolis"|
                 CITY == "Kansas City" | CITY == "Knoxville"|
                 CITY == "Louisville" | CITY == "Memphis"|
                 CITY == "Nashville" | CITY == "Oklahoma City"|
                 CITY == "Omaha" | CITY == "St. Louis"|
                 CITY == "Tulsa")
  df$MSA<-NA
  df$MSA[df$CITY == "Birmingham"] = 13820
  df$MSA[df$CITY == "Charlotte"] = 16740
  df$MSA[df$CITY == "Cincinnati"] = 17140
  df$MSA[df$CITY == "Columbus"] = 18140
  df$MSA[df$CITY == "Grand Rapids"] = 24340
  df$MSA[df$CITY == "Greensboro"] = 24660
  df$MSA[df$CITY == "Greenville"] = 24860
  df$MSA[df$CITY == "Indianapolis"] = 26900
  df$MSA[df$CITY == "Kansas City"] = 28140
  df$MSA[df$CITY == "Knoxville"] = 28940
  df$MSA[df$CITY == "Louisville"] = 31140
  df$MSA[df$CITY == "Memphis"] = 32820
  df$MSA[df$CITY == "Nashville"] = 34980
  df$MSA[df$CITY == "Oklahoma City"] = 36420
  df$MSA[df$CITY == "Omaha"] = 36540
  df$MSA[df$CITY == "St. Louis"] = 41180
  df$MSA[df$CITY == "Tulsa"] = 46140
  df$volunteer_pct[substr(df$volunteer_pct,
                          nchar(df$volunteer_pct),
                          nchar(df$volunteer_pct)) == "%"] = substr(df$volunteer_pct[substr(df$volunteer_pct,
                                                                                            nchar(df$volunteer_pct),
                                                                                            nchar(df$volunteer_pct)) == "%"], 1, nchar(df$volunteer_pct)-1)
  df$volunteer_pct = as.numeric(df$volunteer_pct)
  df%<>%select(volunteer_pct, Year, MSA, city = CITY)
  df
}
#####################################################################################
#Social Support
#####################################################################################
#Reading in and tidying data
sc_data_5_6 <- cbp_read("/input data/qp_input_data/Social Support 5_6", starting_year = 2005)
sc_data_5_6 %<>% select(naics, FIPS, year, baseline, current, est)

sc_data_7_14 <- cbp_read("/input data/qp_input_data/Social Support 7_14", starting_year = 2007)
sc_data_7_14 %<>% select(naics, FIPS, year, baseline, current, est)

sc_data_15 <- read_csv("~/Desktop/glp_website/input data/qp_input_data/cbp15co.txt")
sc_data_15$year = 2015
sc_data_15%<>%mutate(FIPS = paste(FIPSTATE, FIPSCTY, sep = ''))%>%
  pull_peers_FIPS(.)%>%
  select(naics = NAICS, FIPS, year, baseline, current, est = EST)

sc_data<-bind_rows(sc_data_5_6, sc_data_7_14)
sc_data<-bind_rows(sc_data, sc_data_15)

#Add population
pop<-read_csv("~/Desktop/glp_website/input data/qp_input_data/population_data.csv", col_types = cols(
  population = col_integer(),
  FIPS = col_character(),
  year = col_integer()
))
sc_data$FIPS[sc_data$FIPS == "01073"]<-1073 
sc_data<-left_join(sc_data, pop, by = c("FIPS", "year"))


sc_data_no<-sc_data%>%filter(naics == 813410 | naics == 713950|
                               naics == 713910 | naics == 713940|
                               naics == 711211 | naics == 813110|
                               naics == 813940 | naics == 813930|
                               naics == 813910 | naics == 813920)%>%
  filter(!(FIPS == 29189 | FIPS == 29510))%>%
  group_by(year, FIPS, baseline, current, population)%>%
  summarize(ss_est = sum(est))

stl_sc<-sc_data%>%filter(naics == 813410 | naics == 713950|
                           naics == 713910 | naics == 713940|
                           naics == 711211 | naics == 813110|
                           naics == 813940 | naics == 813930|
                           naics == 813910 | naics == 813920)%>%
  filter(FIPS == 29189 | FIPS == 29510)%>%
  group_by(year, baseline, current, population)%>%
  summarize(ss_est = sum(est))%>%
  ungroup(.)%>%
  group_by(year, baseline, current)%>%
  summarize(ss_est = sum(ss_est), population = sum(population))
stl_sc$FIPS <- NA
stl_sc$FIPS <- "0"

sc_data <- bind_rows(sc_data_no, stl_sc)
sc_data%<>%mutate(ss_est_per_10000 = (ss_est/population)*10000)

sc_data$FIPS<-as.numeric(sc_data$FIPS)

qp_data_fips<-sc_data

#####################################################################################
#MSA PCT Core County Population 2010-2016
#####################################################################################

fips_core_county_pop<-read_csv("~/Desktop/glp_website/input data/qp_input_data/population_data.csv")

#Combine St Louis County and City
st_lou<-fips_core_county_pop%>%
  filter(FIPS == 29510| FIPS == 29189)%>%
  group_by(year)%>%
  summarize(population = sum(population))
st_lou$FIPS<-0

fips_core_county_pop%<>%filter(!(FIPS == 29510 | FIPS == 29189))
fips_core_county_pop = rbind(fips_core_county_pop, st_lou)

msa_fips_key<-read_csv("~/Desktop/glp_website/input data/qp_input_data/changed_msa_counties.csv")
msa_fips_key%<>%pull_peers_FIPS(.)%>%
  distinct(MSA, .keep_all = TRUE)%>%
  select(FIPS, MSA)
msa_fips_key$FIPS[msa_fips_key$MSA == 41180]<- 0

fips_core_county_pop<-left_join(fips_core_county_pop, msa_fips_key, by = "FIPS")
fips_core_county_pop%<>%filter(year >= 2010)%>%
  dplyr::rename(Year = year)

msa_pop_est<-read_csv("~/Desktop/glp_website/input data/qp_input_data/cbsa-est2016-alldata.csv", n_max = 1581)
msa_pop_est%<>%filter(LSAD == "Metropolitan Statistical Area")%>%
  pull_peers_MSA(.)%>%
  select(CBSA, POPESTIMATE2010:POPESTIMATE2015)%>%
  gather(POPESTIMATE2010:POPESTIMATE2015, key = 'Year',value = population_estimate)%>%
  dplyr::rename(MSA = CBSA)

msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2010"] = (2010)
msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2011"] = (2011)
msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2012"] = (2012)
msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2013"] = (2013)
msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2014"] = (2014)
msa_pop_est$Year[msa_pop_est$Year == "POPESTIMATE2015"] = (2015)
msa_pop_est$Year = as.numeric(msa_pop_est$Year)

fips_core_county_pop<-left_join(fips_core_county_pop, msa_pop_est, by = c("MSA", "Year"))
fips_core_county_pop%<>%mutate(pct_pop_core_county = 100*population/population_estimate)%>%
  dplyr::rename(core_county_pop = population,
                msa_population_estimate = population_estimate,
                year = Year)%>%
  pull_peers_FIPS(.)%>%
  select(FIPS, year, MSA,msa_population_estimate, pct_pop_core_county)


qp_data_fips<-left_join(qp_data_fips, fips_core_county_pop, by = c("year", "FIPS"))

#####################################################################################
#Read in Food insecurity
#####################################################################################

food_insec<-read_csv("~/Desktop/glp_website/input data/qp_input_data/GLP counties food insecure_PCT.csv")

food_insec%<>%
  pull_peers_FIPS(.)%>%
  dplyr::rename(year = Year)%>%
  select(city, FIPS, year, food_insecure_overall, food_insecure_child)

weights<-read_csv("~/Desktop/glp_website/input data/qp_input_data/FIPS_two_stl.csv", col_types = cols(FIPS = col_integer()))
food_insec<-left_join(food_insec, weights, by = c("city", "FIPS"))

st_lou<-food_insec%>%
  filter(FIPS == 29189 | FIPS == 29510)%>%
  group_by(year, city)%>%
  summarise(food_insecure_overall = weighted.mean(food_insecure_overall, weights),
            food_insecure_child = weighted.mean(food_insecure_child, weights))
st_lou$FIPS<-0
st_lou%<>%select(year, city, food_insecure_overall, food_insecure_child, FIPS)

food_insec%<>%select(-c(county, state, weights))
food_insec <- bind_rows(food_insec, st_lou)

qp_data_fips<-left_join(qp_data_fips, food_insec, by = c("year", "FIPS"))

#####################################################################################
#Food Desert Data Analysis
#####################################################################################

fd_data <- read_csv("~/Desktop/glp_website/input data/qp_input_data/food_desert_2015.csv",
              col_types = cols(laasian20 = col_double(),
                               lanhopi20 = col_double(),
                               lanhopi20share = col_double(),
                               laasian20share = col_double(),
                               laaian20share = col_double(),
                               laaian20 = col_double(),
                               laomultir20 = col_double(),
                               laomultir20share = col_double(),
                               lahisp20 = col_double(),
                               lahisp20share = col_double()))

#Creating FIPS Codes w/ only the first five digits of tract codes
FIPS = substr(fd_data$CensusTract, 1,5)
FIPS = as.numeric(FIPS)
fd_data$FIPS = NA
fd_data$FIPS = FIPS

#Obtain Total Population
pop <- fd_data %>%
  pull_peers_FIPS(.) %>%
  group_by(FIPS) %>%
  summarise(total_city_pop = sum(POP2010),
            total_city_households = sum(OHU2010))

fd_data<-fd_data%>%
  pull_peers_FIPS(.)%>%
  select(c(CensusTract:LILATracts_Vehicle,LALOWI1_10, LALOWI05_10,
           lahunvhalf, lahunv1,HUNVFlag,LowIncomeTracts,
           FIPS, baseline,current))%>%
  select(-c(GroupQuartersFlag,NUMGQTRS,PCTGQTRS, LILATracts_1And20))

fd_data<-inner_join(fd_data, pop, by = "FIPS")

fd_data$FIPS[fd_data$FIPS==29189]<-0
fd_data$FIPS[fd_data$FIPS==29510]<-0
fd_data$total_city_pop[fd_data$FIPS==0] = 1318248
fd_data$total_city_households[fd_data$FIPS==0] = 546822

#Compute Food Desert Vehicle Statistics
#The GLP Standard Metric
# 1. Number of households who have no vehicle
# and live more than 1/2 a mile away from a supermarket, that also live in
# a low income census tract (per 100,000 households).

fd_data <- fd_data %>%
  filter(LowIncomeTracts == 1) %>%
  group_by(FIPS,
           total_city_pop,
           total_city_households,
           current,
           baseline) %>%
  summarise(
    est_food_desert_households = sum(lahunvhalf)
    #Total households without a car and beyond
    #1/2 mile from a supermarket in a Food Desert
    #Census tract determined by vehicle access and
    #1/2 mile
  ) %>%
  mutate(est_food_desert_households_per100000_lowIncTract =
           est_food_desert_households / total_city_households * 100000)
#Grocery Store estimates are from a 2010 study. Population estimates are from 2015.
fd_data$year<-2015
fd_data = ungroup(fd_data)
fd_data%<>%select(-c(total_city_pop,total_city_households, current, baseline))

qp_data_fips<-left_join(qp_data_fips, fd_data, by = c("FIPS", "year"))

write_csv(qp_data_fips, "~/Desktop/glp_website/output data/qp_data_fips.csv")

#####################################################################################
#Volunteer Data Analysis
#####################################################################################

v_2015 <- read_csv("~/Desktop/glp_website/input data/qp_input_data/volunteer2015.csv")

v_2015$MSA <- NA
v_2015$MSA[v_2015$CITY == "Birmingham-Hoover, AL"] = 13820
v_2015$MSA[v_2015$CITY == "Charlotte-Gastonia-Concord, NC-SC"] = 16740
v_2015$MSA[v_2015$CITY == "Cincinnati-Middletown, OH-KY-IN"] = 17140
v_2015$MSA[v_2015$CITY == "Columbus, OH"] = 18140
v_2015$MSA[v_2015$CITY == "Grand Rapids - Wyoming, MI"] = 24340
v_2015$MSA[v_2015$CITY == "Greensboro-High Point, NC"] = 24660
v_2015$MSA[v_2015$CITY == "Greenville, SC"] = 24860
v_2015$MSA[v_2015$CITY == "Indianapolis, IN"] = 26900
v_2015$MSA[v_2015$CITY == "Kansas City, MO-KS"] = 28140
v_2015$MSA[v_2015$CITY == "Knoxville, TN"] = 28940
v_2015$MSA[v_2015$CITY == "Louisville, KY-IN"] = 31140
v_2015$MSA[v_2015$CITY == "Memphis, TN-MS-AR"] = 32820
v_2015$MSA[v_2015$CITY == "Nashville-Davidson-Murfreesboro, TN"] = 34980
v_2015$MSA[v_2015$CITY == "Oklahoma City, OK"] = 36420
v_2015$MSA[v_2015$CITY == "Omaha-Council Bluffs, NE-IA"] = 36540
v_2015$MSA[v_2015$CITY == "St. Louis, MO-IL"] = 41180
v_2015$MSA[v_2015$CITY == "Tulsa, OK"] = 46140

v_2015$`2015` = as.numeric(substr(v_2015$`2015`, 1, nchar(v_2015$`2015`)-1))
v_2015$`2015` = as.numeric(v_2015$`2015`)
v_2015$Year <- NA
v_2015$Year = 2015
v_2015%<>%dplyr::rename("volunteer_pct" = `2015`)%>%
  select(volunteer_pct, Year, MSA)

v_2014<-volunteer_read("~/Desktop/glp_website/input data/qp_input_data/volunteer2014.csv")
v_2013<-volunteer_read("~/Desktop/glp_website/input data/qp_input_data/volunteer2013.csv")
v_2012<-volunteer_read("~/Desktop/glp_website/input data/qp_input_data/volunteer2012.csv")
v_2011<-volunteer_read("~/Desktop/glp_website/input data/qp_input_data/volunteer2011.csv")

#Add City Names to 2015
key<-v_2014%>%
  select(MSA, city)
v_2015 <- left_join(v_2015, key, by = "MSA")


v_data = rbind(v_2011, v_2012)
v_data <- v_data %>%
  rbind(v_2013)%>%
  rbind(v_2014)%>%
  rbind(v_2015)
v_data$current <- 1
v_data%<>%dplyr::rename(year = Year)

qp_data_msa <- v_data
write_csv(qp_data_msa, "~/Desktop/glp_website/output data/qp_data_msa.csv")
```

To be continued...
