---
title: "QOP Graphing"
output: html_notebook
---

Loading Libraries
```{r}
library(tidyverse)
library(ggthemes)
library(reshape2)
library(showtext)
library(classInt)
```

Necessary Functions
```{r}
rank_and_nb_group<-function(df, var, order="Descending", peers="Current",
                            plot_title="", y_title = "Percent", caption_text = ""){
  df$var <- df[[var]]
  if(peers=="Current"){
    df<-subset(df,current ==1)
  }
  if(peers=="Baseline"){
    df<-subset(df,baseline ==1)
  }
  if(order=="Descending"){
    d.order<-df[order(-df$var),]
  }
  if(order=="Ascending"){
    d.order<-df[order(df$var),]
  }
  ranks<-1:length(df$var)
  d.rank<-cbind(d.order,ranks)
  names<-paste(d.rank$ranks,".",sep="")
  names<-paste(names,d.rank$city)
  d.graph<-cbind(d.rank,names)
  
  breaks <- classIntervals(d.graph$var,3,style="jenks")
  d.graph$color <- NA
  d.graph$color[d.graph$var<=breaks$brks[2]] <- "green"
  d.graph$color[d.graph$var>breaks$brks[2] & d.graph$var<=breaks$brks[3]] <- "yellow"
  d.graph$color[d.graph$var>breaks$brks[3]] <- "red"
  d.graph$round <- format(round(d.graph$var,1),nsmall=1)
  d.graph$textfont <- "Museo Sans 300"
  d.graph$textfont[d.graph$city == "Louisville"] <- "Museo Sans 300 Italic"
  d.graph$linecolor <- "white"
  d.graph$linecolor[d.graph$city == "Louisville"] <- "#00a9b7"
  d.graph$textcolor <- "black"
  d.graph$textcolor[d.graph$city == "Louisville"] <- "#00a9b7"
  
  
  p <- ggplot(data=d.graph,aes(x=factor(names, levels=rev(unique(names))),
                               y=var,fill=factor(color)))+guides(fill=FALSE)
  p <- p+geom_bar(stat="identity",color=rev(d.graph$linecolor), size = 1)+coord_flip()+theme_tufte()
  if(order=="Ascending"){
    p <- p+scale_fill_manual(values=c("#96ca4f","#db2834","#ffd600"))
  }
  if(order=="Descending"){
    p <- p+scale_fill_manual(values=c("#db2834","#96ca4f","#ffd600"))
  }
  p <- p + theme(text = element_text(family = "Museo Sans 300"),
                 plot.title = element_text(size = 18, hjust = 0.5),
                 axis.text.y=element_text(hjust=0, family = rev(d.graph$textfont),
                                          size=12, color = rev(d.graph$textcolor)),
                 axis.ticks=element_blank(),
                 axis.text.x = element_blank(),
                 plot.caption = element_text(),
                 plot.subtitle = element_text(hjust = 0.5))
  p <- p+geom_text(aes(label=round),hjust=1.1, size=5, family = "Museo Sans 300")
  p <- p+labs(title = plot_title, y= y_title,
              x = "", caption = caption_text)
  p
}

##rolling mean functions for trendlines
rollmean3 <- function(x){
  n <- length(x)
  y <- NA
  for(i in 1:n){
    y[i] <- mean(c(x[i-1],x[i],x[i+1]))
    y[1] <- NA
  }
  y
}

rollmean5 <- function(x){
  n <- length(x)
  y <- NA
  for(i in 1:n){
    y[i] <- mean(c(x[i-2],x[i-1],x[i],x[i+1],x[i+2]))
    y[1] <- NA
    y[2] <- NA
  }
  y
}

##
graph_trendline<-function(df,var, plot_title="",y_title="Percent", peers = "Current", 
                          caption_text = "", subtitle_text = "", rollmean = 3,
                          break_settings = seq(2005, 2015, 2), xmin = 1996, xmax = 2016){
  df$var <- df[[var]]
  df = df %>% filter(year != 2016)
  
  if(peers=="Current"){
    df.wol <- subset(df,current == 1 & FIPS!=21111)
  }
  
  if(peers=="Baseline"){
    df.wol <- subset(df,baseline == 1 & FIPS!=21111)
  }
  
  output_wol = df %>% 
    group_by(year) %>%
    summarise(first_quarter = quantile(var, prob = 0.25, na.rm = TRUE),
              mean = mean(var),
              third_quarter = quantile(var, prob = 0.75, na.rm = TRUE))
  
  lville = df %>% 
    filter(FIPS == 21111) %>% 
    select(var, year)
  
  dat = full_join(lville, output_wol, by = "year")
  
  if (rollmean == 3){
    dat$var = rollmean3(dat$var)
    dat$first_quarter = rollmean3(dat$first_quarter)
    dat$mean = rollmean3(dat$mean)
    dat$third_quarter = rollmean3(dat$third_quarter)
    dat <- dat %>% filter(year > 2005 & year < 2015)
  }
  
  if (rollmean == 5){
    dat$var = rollmean5(dat$var)
    dat$first_quarter = rollmean5(dat$first_quarter)
    dat$mean = rollmean5(dat$mean)
    dat$third_quarter = rollmean5(dat$third_quarter)
    dat = dat %>% filter(year > 2006 & year < 2014)
  }
  
  data_long <- melt(dat, id="year")
  data_long$variable = factor(data_long$variable, levels = c("var", "third_quarter", "mean", "first_quarter"))
  
  p <- ggplot(data=data_long,aes(x=year,y=value,colour=variable,linetype=variable))+
    geom_point(size = 1.8)+
    geom_line(size = 1)
  p <- p + theme_bw()
  midpoint <- (max(data_long$value, na.rm = TRUE)+min(data_long$value, na.rm = TRUE))/2
  border_space <- .1 * midpoint
  p <- p + ylim(c(min(data_long$value, na.rm = TRUE) - border_space, max(data_long$value, na.rm=TRUE) + border_space))
  p<-p+scale_x_continuous(limits = c(xmin, xmax), breaks = break_settings)
  cPalette <- c("#00a9b7","grey50", "black","grey50")
  p<-p+scale_colour_manual(values=cPalette,
                           labels=c("Louisville", "75th Percentile", "Peer City Mean", "25th Percentile"))+
    scale_linetype_manual(values=c("solid","dashed","dashed","dashed"),
                          labels=c("Louisville", "75th Percentile", "Peer City Mean", "25th Percentile"))
  p<-p+theme(text = element_text(family = "Museo Sans 300"),
             legend.title=element_blank(),
             legend.position = "top",
             axis.text=element_text(size=12, family = "Museo Sans 300"),
             axis.ticks.y=element_blank(),
             plot.title=element_text(size=18, hjust=.5, family = "Museo Sans 300",
                                     margin=margin(b=10,unit="pt")),
             legend.text=element_text(size=12, family = "Museo Sans 300"),
             plot.caption = element_text(family = "Museo Sans 300"),
             plot.subtitle = element_text(family = "Museo Sans 300", hjust = 0.5))
  p<-p+labs(title=plot_title,x="Year",
            y=y_title, caption = caption_text, subtitle = subtitle_text)
  p
}

graph_trendline_msa<-function(df,var, plot_title="",y_title="Percent", peers = "Current", 
                              caption_text = "", subtitle_text = "", rollmean = 3,
                              break_settings = seq(2005, 2015, 2), xmin = 1996, xmax = 2016){
  df$var <- df[[var]]
  df = df %>% filter(year != 2016)
  if(peers=="Current"){
    df.wol <- filter(df,current == 1 & MSA!=31140)
  }
  if(peers=="Baseline"){
    df.wol <- filter(df,baseline == 1 & MSA!=31140)
  }
  output_wol = df %>% 
    group_by(year) %>%
    summarise(first_quarter = quantile(var, prob = 0.25, na.rm = TRUE),
              mean = mean(var),
              third_quarter = quantile(var, prob = 0.75, na.rm = TRUE))
  lville = df %>% 
    filter(MSA == 31140) %>% 
    select(var, year)
  dat = full_join(lville, output_wol, by = "year")
  if (rollmean == 3){
    dat$var = rollmean3(dat$var)
    dat$first_quarter = rollmean3(dat$first_quarter)
    dat$mean = rollmean3(dat$mean)
    dat$third_quarter = rollmean3(dat$third_quarter)
    dat <- dat %>% filter(year > 2003 & year < 2014)
  }
  if (rollmean == 5){
    dat$var = rollmean5(dat$var)
    dat$first_quarter = rollmean5(dat$first_quarter)
    dat$mean = rollmean5(dat$mean)
    dat$third_quarter = rollmean5(dat$third_quarter)
    dat = dat %>% filter(year > 2006 & year < 2014)
  }
  dat
  data_long <- melt(dat, id="year")
  data_long$variable = factor(data_long$variable, levels = c("var", "third_quarter", "mean", "first_quarter"))
  p <- ggplot(data=data_long,aes(x=year,y=value,colour=variable,linetype=variable))+
    geom_point(size = 1.8)+
    geom_line(size = 1)
  p <- p + theme_bw()
  midpoint <- (max(data_long$value)+min(data_long$value))/2
  border_space <- .1 * midpoint
  p <- p + ylim(c(min(data_long$value) - border_space, max(data_long$value + border_space)))
  p<-p+scale_x_continuous(limits = c(xmin, xmax), breaks = break_settings)
  cPalette <- c("#00a9b7","grey50", "black","grey50")
  p<-p+scale_colour_manual(values=cPalette,
                           labels=c("Louisville", "25th Percentile", "Peer City Mean", "75th Percentile"))+
    scale_linetype_manual(values=c("solid","dashed","dashed","dashed"),
                          labels=c("Louisville", "25th Percentile", "Peer City Mean", "75th Percentile"))
  p<-p+theme(text = element_text(family = "Museo Sans 300"),
             legend.title=element_blank(),
             legend.position = "top",
             axis.text=element_text(size=12, family = "Museo Sans 300"),
             axis.ticks.y=element_blank(),
             plot.title=element_text(size=18, hjust=.5, family = "Museo Sans 300",
                                     margin=margin(b=10,unit="pt")),
             legend.text=element_text(size=12, family = "Museo Sans 300"),
             plot.caption = element_text(family = "Museo Sans 300"),
             plot.subtitle = element_text(family = "Museo Sans 300", hjust = 0.5))
  p<-p+labs(title=plot_title,x="Year",
            y=y_title, caption = caption_text, subtitle = subtitle_text)
  p
}

#Made a few special adjustments for the net migration variable.
rank_and_nb_group_mig<-function(df, var, order="Descending", peers="Current",
                            plot_title="", y_title = "Percent", caption_text = ""){
  df$var <- df[[var]]
  if(peers=="Current"){
    df<-subset(df,current ==1)
  }
  if(peers=="Baseline"){
    df<-subset(df,baseline ==1)
  }
  if(order=="Descending"){
    d.order<-df[order(-df$var),]
  }
  if(order=="Ascending"){
    d.order<-df[order(df$var),]
  }
  ranks<-1:length(df$var)
  d.rank<-cbind(d.order,ranks)
  names<-paste(d.rank$ranks,".",sep="")
  names<-paste(names,d.rank$city)
  d.graph<-cbind(d.rank,names)
  
  breaks <- classIntervals(d.graph$var,3,style="jenks")
  d.graph$color <- NA
  d.graph$color[d.graph$var<=breaks$brks[2]] <- "green"
  d.graph$color[d.graph$var>breaks$brks[2] & d.graph$var<=breaks$brks[3]] <- "yellow"
  d.graph$color[d.graph$var>breaks$brks[3]] <- "red"
  d.graph$round <- format(round(d.graph$var,0),nsmall=0)
  d.graph$textfont <- "Museo Sans 300"
  d.graph$textfont[d.graph$city == "Louisville"] <- "Museo Sans 300 Italic"
  d.graph$linecolor <- "white"
  d.graph$linecolor[d.graph$city == "Louisville"] <- "#00a9b7"
  d.graph$textcolor <- "black"
  d.graph$textcolor[d.graph$city == "Louisville"] <- "#00a9b7"
  
  
  p <- ggplot(data=d.graph,aes(x=factor(names, levels=rev(unique(names))),
                               y=var,fill=factor(color)))+guides(fill=FALSE)
  p <- p+geom_bar(stat="identity",color=rev(d.graph$linecolor), size = 1)+coord_flip()+theme_tufte()
  if(order=="Ascending"){
    p <- p+scale_fill_manual(values=c("#96ca4f","#db2834","#ffd600"))
  }
  if(order=="Descending"){
    p <- p+scale_fill_manual(values=c("#db2834","#96ca4f","#ffd600"))
  }
  p <- p + theme(text = element_text(family = "Museo Sans 300"),
                 plot.title = element_text(size = 18, hjust = 0.5),
                 axis.text.y=element_text(hjust=0, family = rev(d.graph$textfont),
                                          size=12, color = rev(d.graph$textcolor)),
                 axis.ticks=element_blank(),
                 axis.text.x = element_blank(),
                 plot.caption = element_text(),
                 plot.subtitle = element_text(hjust = 0.5))
  p <-
    p + geom_text(
    aes(label = round),
    hjust = ifelse(d.graph$var > 1000, 1.1, ifelse(
    d.graph$var > 0, .2, ifelse(d.graph$var > -1000, 1.0, -.1))),
    size = 5,
    family = "Museo Sans 300")
  p <- p+labs(title = plot_title, y= y_title,
              x = "", caption = caption_text)
  p
}
```

Read in data and set working directory
```{r}
setwd("~/Desktop/glp_website/output data")
qp_data_fips<-read_csv("qp_data_fips.csv")
qp_data_msa<-read_csv("qp_data_msa.csv")
font.add("Museo Sans 300", "/Users/BryceRowland/Desktop/GLP/R Code/MuseoSans_300.otf")
font.add("Museo Sans 300 Italic", "/Users/BryceRowland/Desktop/GLP/R Code/MuseoSans_300_Italic.otf")
```

Graphing Ranking Graphs
```{r}
setwd("~/Desktop/glp_website/Images/QP Images")
#Ranking Graphs
jpeg("qp_food_insecurity_child_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  filter(qp_data_fips, year == 2015),
  'food_insecure_child',
  order = "Ascending",
  plot_title = "Food Insecurity Rate, 2015",
  caption_text = "Source: Greater Louisville Project \nData from Feeding America, Map the Meal Gap"
)
showtext.end()
dev.off()

jpeg("qp_food_insecurity_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  filter(qp_data_fips, year == 2015),
  'food_insecure_overall',
  order = "Ascending",
  plot_title = "Food Insecurity Rate, 2015",
  caption_text = "Source: Greater Louisville Project \nData from Feeding America, Map the Meal Gap"
)
showtext.end()
dev.off()

jpeg("qp_pct_pop_core_county.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  filter(qp_data_fips, year == 2015),
  'pct_pop_core_county',
  order = "Descending",
  plot_title = "Population Living in Core MSA County, 2015",
  caption_text = "Source: Greater Louisville Project \nData from US Census Bureau, MSA"
)
showtext.end()
dev.off()

jpeg("qp_food_desert_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  filter(qp_data_fips, year == 2015),
  'est_food_desert_households_per100000_lowIncTract',
  order = "Ascending",
  plot_title = "Households Living in a Low Income Census Tract\nWith No Vehicle and Limited Access to Food\n(per 100,000 households), 2010",
  caption_text = "Source: Greater Louisville Project \nData from USDA, Food Atlas 2015"
)
showtext.end()
dev.off()

jpeg("qp_volunteer_rate_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  filter(qp_data_msa, year == 2014),
  "volunteer_pct",
  plot_title = "Volunteer Rate, 2014",
  caption_text = "Source: Greater Louisville Project\nData from the Corporation for National and Community Service\nMSA Groupings are 2003 OMB standards"
)
showtext.end()
dev.off()

jpeg("qp_social_support_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'ss_est_per_10000',
  order = "Descending",
  y_title = "Membership Associations per 10,000 residents",
  plot_title = "Number of Membership Associations per 10,000 residents, 2015",
  caption_text = "Source: Greater Louisville Project \nData from CBP Statistics from US Census"
)
showtext.end()
dev.off()

jpeg("qp_commute_time_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'commute_time',
  order = "Ascending",
  y_title = "Commute Time (minutes)",
  plot_title = "Commute Time, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_severe_burdened_households_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'burdened_households',
  order = "Ascending",
  y_title = "Percent of Households",
  plot_title = "Burdened Households, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_housing_price_index_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'housing_price_index',
  order = "Ascending",
  y_title = "Index Score",
  plot_title = "Housing Price Index, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_home_ownership_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'home_ownership',
  order = "Descending",
  y_title = "Percent",
  plot_title = "Home Ownership, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_income_inequality_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'income_inequality',
  order = "Ascending",
  y_title = "Ratio",
  plot_title = "Income Inequality, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_disconnected_youth_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'disconnected_youth',
  order = "Ascending",
  y_title = "Percent",
  plot_title = "Disconnected Youth, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_net_migration_flow_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group_mig(
  as.data.frame(filter(qp_data_fips, year == 2013)),
  'net_migration_flow',
  order = "Descending",
  y_title = "Net Migration Flow",
  plot_title = "Net Migration Flow, 2013",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_racial_geography_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'racial_geography',
  order = "Ascending",
  y_title = "Index Score",
  plot_title = "Racial Dissimilarity Index, 2015",
  caption_text = "Source: Greater Louisville Project \nData from GeoFRED"
)
showtext.end()
dev.off()

jpeg("qp_violent_crime_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'violent_crime',
  order = "Ascending",
  y_title = "Violent Crimes per 100,000",
  plot_title = "Violent Crime",
  caption_text = "Source: Greater Louisville Project \nData from the Robert Wood Johnson Foundation 2017 County Health Rankings"
)
showtext.end()
dev.off()

jpeg("qp_injury_death_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'violent_crime',
  order = "Ascending",
  y_title = "Injury Mortality Rate per 100,000",
  plot_title = "Injury Deaths",
  caption_text = "Source: Greater Louisville Project \nData from the Robert Wood Johnson Foundation 2017 County Health Rankings"
)
showtext.end()
dev.off()

jpeg("qp_air_pollution_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'air_pollution',
  order = "Ascending",
  y_title = "Average Daily Amount of Fine Particulate Matter in Micrograms per Cubic Meter",
  plot_title = "Air Pollution",
  caption_text = "Source: Greater Louisville Project \nData from the Robert Wood Johnson Foundation 2017 County Health Rankings"
)
showtext.end()
dev.off()

jpeg("qp_severe_housing_problems_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'severe_housing_problems',
  order = "Ascending",
  y_title = "Percent",
  plot_title = "Severe Housing Problems",
  caption_text = "Source: Greater Louisville Project \nData from the Robert Wood Johnson Foundation 2017 County Health Rankings"
)
showtext.end()
dev.off()

jpeg("qp_driving_alone_to_work_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2015)),
  'driving_alone_to_work',
  order = "Ascending",
  y_title = "Percent",
  plot_title = "Driving Alone to Work",
  caption_text = "Source: Greater Louisville Project \nData from the Robert Wood Johnson Foundation 2017 County Health Rankings"
)
showtext.end()
dev.off()

jpeg("qp_multidimensional_poverty_rankings.jpg", 900, 600, res = 100)
showtext.begin()
rank_and_nb_group(
  as.data.frame(filter(qp_data_fips, year == 2014)),
  'percent_in_mpi',
  order = "Ascending",
  y_title = "Percent",
  plot_title = "Multidimensional Poverty",
  caption_text = "Source: Greater Louisville Project \nData from American Community Survey"
)
showtext.end()
dev.off()
```

Trendline Graphs
```{r}
setwd("~/Desktop/glp_website/Images/QP Images")
jpeg("qp_food_insecurity_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(
  qp_data_fips,
  'food_insecure_overall',
  plot_title = "Food Insecurity Rate",
  rollmean = 1,
  caption_text = "Source: Greater Louisville Project \nData from Feeding America, Map the Meal Gap",
  break_settings = seq(2013, 2015, 2),
  xmin = 2012.5,
  xmax = 2015.5
)
showtext.end()
dev.off()

jpeg("qp_food_insecurity_child_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(
  qp_data_fips,
  'food_insecure_child',
  plot_title = "Child Food Insecurity Rate",
  rollmean = 1,
  caption_text = "Source: Greater Louisville Project \nData from Feeding America, Map the Meal Gap",
  break_settings = seq(2013, 2015, 2),
  xmin = 2012.5,
  xmax = 2015.5
)
showtext.end()
dev.off()

jpeg("pct_pop_living_in_core_county_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(qp_data_fips, "pct_pop_core_county",
                    plot_title = "Percent Population Living in Core MSA County",
                    caption_text = "Source: Greater Louisville Project\nData frome US Census Bureau, MSA",
                    xmin = 2010, xmax = 2015,
                    rollmean = 1)
showtext.end()
dev.off()

jpeg("volunteer_rate_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline_msa(
  filter(qp_data_msa, year<=2014),
  var = "volunteer_pct",
  rollmean = 1,
  xmin = 2011,
  xmax = 2014,
  plot_title = "Volunteer Rate",
  caption_text = "Source: Greater Louisville Project\nData from the Corporation for National and Community Service\nMSA Groupings are 2003 OMB standards"
)
showtext.end()
dev.off()

jpeg("qp_social_support_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'ss_est_per_10000', rollmean = 1,
                plot_title = "Number of Membership Associations per 10,000 residents, 2015",
                y_title = "Membership Associations per 10,000 residents",
                caption_text = "Source: Greater Louisville Project \nData from CBP Statistics from US Census",
                xmin = 2005, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_net_migration_flow_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'net_migration_flow', rollmean = 1,
                plot_title = "Net Migration Flow",
                y_title = "Net Migration Flow",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2009, xmax = 2013)
showtext.end()
dev.off()

jpeg("qp_commute_time_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'commute_time', rollmean = 1,
                plot_title = "Commute Time",
                y_title = "Commute Time (minutes)",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2009, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_severe_burdened_households_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'burdened_households', rollmean = 1,
                plot_title = "Burdened Households",
                y_title = "Percent",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2010, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_housing_price_index_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'housing_price_index', rollmean = 1,
                plot_title = "Housing Price Index",
                y_title = "Index Score",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2010, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_home_ownership_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'home_ownership', rollmean = 1,
                plot_title = "Home Ownership",
                y_title = "Percent",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2009, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_income_inequality_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'income_inequality', rollmean = 1,
                plot_title = "Income Inequality",
                y_title = "Ratio",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2010, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_disconnected_youth_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'disconnected_youth', rollmean = 1,
                plot_title = "Disconnected Youth",
                y_title = "Ratio",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2009, xmax = 2015)
showtext.end()
dev.off()

jpeg("qp_racial_geography_trendline.jpg", 900, 600, res = 100)
showtext.begin()
graph_trendline(as.data.frame(qp_data_fips), var = 'racial_geography', rollmean = 1,
                plot_title = "Racial Dissimilarity Index",
                y_title = "Index Score",
                caption_text = "Source: Greater Louisville Project \nData from GeoFRED",
                xmin = 2009, xmax = 2015)
showtext.end()
dev.off()
```






